CREATE TABLE `projectBudgetLines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetId` int NOT NULL,
	`projectId` int NOT NULL,
	`stageId` int,
	`costItemId` int,
	`accountId` int,
	`lineType` enum('revenue','cost','tax','zakat','profit') NOT NULL,
	`code` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`amount` decimal(14,2) NOT NULL DEFAULT '0',
	`taxBasis` enum('pre_tax','inclusive','not_applicable') NOT NULL DEFAULT 'pre_tax',
	`source` varchar(64) NOT NULL DEFAULT 'user_import',
	`sortOrder` int NOT NULL DEFAULT 0,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projectBudgetLines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projectBudgets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`projectId` int NOT NULL,
	`budgetCode` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`currency` varchar(8) NOT NULL DEFAULT 'SAR',
	`status` enum('draft','approved','locked') NOT NULL DEFAULT 'approved',
	`plannedRevenue` decimal(14,2) NOT NULL DEFAULT '0',
	`plannedCost` decimal(14,2) NOT NULL DEFAULT '0',
	`plannedTax` decimal(14,2) NOT NULL DEFAULT '0',
	`plannedZakat` decimal(14,2) NOT NULL DEFAULT '0',
	`plannedProfit` decimal(14,2) NOT NULL DEFAULT '0',
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projectBudgets_id` PRIMARY KEY(`id`),
	CONSTRAINT `projectBudgets_budgetCode_unique` UNIQUE(`budgetCode`)
);
