import {
  boolean,
  date,
  decimal,
  int,
  index,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core";

export const companies = mysqlTable("companies", {
  id: int("id").autoincrement().primaryKey(),
  legalName: varchar("legalName", { length: 255 }).notNull(),
  businessType: mysqlEnum("businessType", ["real_estate_developer", "contractor"]).default("real_estate_developer").notNull(),
  tradeName: varchar("tradeName", { length: 255 }),
  commercialRegistration: varchar("commercialRegistration", { length: 128 }),
  taxNumber: varchar("taxNumber", { length: 128 }),
  nationalAddress: text("nationalAddress"),
  phone: varchar("phone", { length: 64 }),
  email: varchar("email", { length: 255 }),
  website: varchar("website", { length: 255 }),
  logoUrl: varchar("logoUrl", { length: 2000 }),
  notes: text("notes"),
  isActive: int("isActive").notNull().default(1),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const companyMembers = mysqlTable("companyMembers", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId").notNull(),
  userId: int("userId").notNull(),
  role: mysqlEnum("role", ["owner", "admin", "general_manager", "project_manager", "procurement_manager", "user"]).default("user").notNull(),
  status: mysqlEnum("status", ["active", "invited", "suspended"]).default("active").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin", "general_manager", "project_manager", "procurement_manager", "site_worker"]).default("user").notNull(),
  jobTitle: varchar("jobTitle", { length: 255 }),
  defaultProjectId: int("defaultProjectId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
  passwordHash: varchar("passwordHash", { length: 255 }),
  mustChangePassword: int("mustChangePassword").notNull().default(0),
});

export const userInvitations = mysqlTable("userInvitations", {
  id: int("id").autoincrement().primaryKey(),
  email: varchar("email", { length: 320 }).notNull(),
  name: varchar("name", { length: 255 }),
  jobTitle: varchar("jobTitle", { length: 255 }).notNull(),
  role: mysqlEnum("role", ["user", "general_manager", "project_manager", "procurement_manager", "site_worker"]).default("user").notNull(),
  projectId: int("projectId"),
  status: mysqlEnum("status", ["pending", "accepted", "cancelled", "expired"]).default("pending").notNull(),
  token: varchar("token", { length: 128 }).notNull().unique(),
  invitedBy: int("invitedBy").notNull(),
  expiresAt: timestamp("expiresAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  passwordHash: varchar("passwordHash", { length: 255 }),
});

export const passwordResetTokens = mysqlTable("passwordResetTokens", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  tokenHash: varchar("tokenHash", { length: 128 }).notNull().unique(),
  expiresAt: timestamp("expiresAt").notNull(),
  usedAt: timestamp("usedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const projects = mysqlTable("projects", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  code: varchar("code", { length: 64 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  status: mysqlEnum("status", ["planning", "active", "paused", "completed", "archived"]).default("planning").notNull(),
  classification: mysqlEnum("classification", ["operational", "administrative"]).default("operational").notNull(),
  projectType: mysqlEnum("projectType", ["real_estate_developer", "real_estate_development", "off_plan_sales", "main_contractor", "subcontractor", "general"]).default("general").notNull(),
  escrowCashAccountId: int("escrowCashAccountId"),
  escrowTrusteeName: varchar("escrowTrusteeName", { length: 255 }),
  escrowStatementReference: varchar("escrowStatementReference", { length: 128 }),
  wipAccountId: int("wipAccountId"),
  wipClosedAt: timestamp("wipClosedAt"),
  wipClosedBy: int("wipClosedBy"),
  wipClosingDocumentId: int("wipClosingDocumentId"),
  contractValue: decimal("contractValue", { precision: 14, scale: 2 }).default("0").notNull(),
  location: varchar("location", { length: 255 }),
  plannedStart: date("plannedStart"),
  plannedEnd: date("plannedEnd"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const projectWorkLocations = mysqlTable("projectWorkLocations", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  latitude: decimal("latitude", { precision: 10, scale: 7 }).notNull(),
  longitude: decimal("longitude", { precision: 10, scale: 7 }).notNull(),
  allowedRadiusMeters: decimal("allowedRadiusMeters", { precision: 10, scale: 2 }).notNull().default("150"),
  isActive: boolean("isActive").default(true).notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, (table) => ({ projectIdIdx: index("projectWorkLocations_projectId_idx").on(table.projectId) }));

export const projectMembers = mysqlTable("projectMembers", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  projectRole: mysqlEnum("projectRole", ["manager", "finance", "input", "reviewer", "viewer"]).default("viewer").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const userOperationPermissions = mysqlTable("userOperationPermissions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  operationKey: varchar("operationKey", { length: 64 }).notNull(),
  mode: mysqlEnum("mode", ["allow", "approval", "deny"]).default("approval").notNull(),
  updatedBy: int("updatedBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const stages = mysqlTable("stages", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  code: varchar("code", { length: 64 }).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  status: mysqlEnum("status", ["planned", "active", "completed", "delayed"]).default("planned").notNull(),
  plannedBudget: decimal("plannedBudget", { precision: 14, scale: 2 }).default("0").notNull(),
  plannedBudgetTaxBasis: mysqlEnum("plannedBudgetTaxBasis", ["pre_tax", "inclusive"]).default("pre_tax").notNull(),
  budgetParentCostItemId: int("budgetParentCostItemId"),
  plannedStart: date("plannedStart"),
  plannedEnd: date("plannedEnd"),
  actualProgress: decimal("actualProgress", { precision: 5, scale: 2 }).default("0").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const projectBudgets = mysqlTable("projectBudgets", {

  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId").notNull(),
  budgetCode: varchar("budgetCode", { length: 64 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  currency: varchar("currency", { length: 8 }).notNull().default("SAR"),
  status: mysqlEnum("status", ["draft", "approved", "locked"]).default("approved").notNull(),
  plannedRevenue: decimal("plannedRevenue", { precision: 14, scale: 2 }).notNull().default("0"),
  plannedCost: decimal("plannedCost", { precision: 14, scale: 2 }).notNull().default("0"),
  plannedTax: decimal("plannedTax", { precision: 14, scale: 2 }).notNull().default("0"),
  plannedZakat: decimal("plannedZakat", { precision: 14, scale: 2 }).notNull().default("0"),
  plannedProfit: decimal("plannedProfit", { precision: 14, scale: 2 }).notNull().default("0"),
  notes: text("notes"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, (table) => ({ projectIdIdx: index("projectBudgets_projectId_idx").on(table.projectId), companyIdIdx: index("projectBudgets_companyId_idx").on(table.companyId) }));

export const projectBudgetLines = mysqlTable("projectBudgetLines", {
  id: int("id").autoincrement().primaryKey(),
  budgetId: int("budgetId").notNull(),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  costItemId: int("costItemId"),
  accountId: int("accountId"),
  lineType: mysqlEnum("lineType", ["revenue", "cost", "tax", "zakat", "profit"]).notNull(),
  code: varchar("code", { length: 64 }).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  amount: decimal("amount", { precision: 14, scale: 2 }).notNull().default("0"),
  taxBasis: mysqlEnum("taxBasis", ["pre_tax", "inclusive", "not_applicable"]).default("pre_tax").notNull(),
  source: varchar("source", { length: 64 }).default("user_import").notNull(),
  sortOrder: int("sortOrder").default(0).notNull(),
  notes: text("notes"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const vendors = mysqlTable("vendors", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId"),
  name: varchar("name", { length: 255 }).notNull(),
  partyType: mysqlEnum("partyType", ["supplier", "customer"]).default("supplier").notNull(),
  entityType: mysqlEnum("entityType", ["individual", "company"]).default("company").notNull(),
  taxNumber: varchar("taxNumber", { length: 128 }),
  commercialRegistration: varchar("commercialRegistration", { length: 128 }),
  nationalAddress: text("nationalAddress"),
  address: text("address"),
  phone: varchar("phone", { length: 64 }),
  email: varchar("email", { length: 255 }),
  iban: varchar("iban", { length: 128 }),
  contact: varchar("contact", { length: 255 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const inventoryItems = mysqlTable("inventoryItems", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId"),
  parentItemId: int("parentItemId"),
  defaultCostItemId: int("defaultCostItemId"),
  code: varchar("code", { length: 64 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  category: varchar("category", { length: 128 }).default("materials").notNull(),
  unit: varchar("unit", { length: 64 }).notNull(),
  minimumStock: decimal("minimumStock", { precision: 14, scale: 3 }).default("0").notNull(),
  isActive: int("isActive").default(1).notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const inventoryMovements = mysqlTable("inventoryMovements", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  costItemId: int("costItemId"),
  itemId: int("itemId").notNull(),
  vendorId: int("vendorId"),
  movementType: mysqlEnum("movementType", ["receipt", "issue", "adjustment_in", "adjustment_out"]).notNull(),
  quantity: decimal("quantity", { precision: 14, scale: 3 }).notNull(),
  unitCost: decimal("unitCost", { precision: 14, scale: 4 }).default("0").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  movementDate: date("movementDate"),
  reference: varchar("reference", { length: 128 }),
  description: text("description"),
  sourceDocumentId: int("sourceDocumentId"),
  purchaseInvoiceId: int("purchaseInvoiceId"),
  contractId: int("contractId"),
  contractItemIndex: int("contractItemIndex"),
  status: mysqlEnum("status", ["draft", "pending_approval", "posted", "cancelled"]).default("pending_approval").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const expenses = mysqlTable("expenses", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId"),
  stageId: int("stageId"),
  vendorId: int("vendorId"),
  costItemId: int("costItemId"),
  reference: varchar("reference", { length: 128 }),
  description: text("description").notNull(),
  unit: varchar("unit", { length: 64 }),
  quantity: decimal("quantity", { precision: 14, scale: 3 }).default("1").notNull(),
  expenseType: varchar("expenseType", { length: 64 }).default("operating").notNull(),
  payrollBeneficiaryType: mysqlEnum("payrollBeneficiaryType", ["company_employee", "worker"]),
  payrollEmployeeId: int("payrollEmployeeId"),
  payrollBeneficiaryName: varchar("payrollBeneficiaryName", { length: 255 }),
  classification: mysqlEnum("classification", ["project", "administrative", "general_cash", "petty_cash"]).default("project").notNull(),
  allocationRatio: decimal("allocationRatio", { precision: 6, scale: 3 }).default("1").notNull(),
  preTaxAmount: decimal("preTaxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  taxRate: decimal("taxRate", { precision: 5, scale: 2 }).default("15").notNull(),
  taxAmount: decimal("taxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  paidAmount: decimal("paidAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["draft", "pending", "approved", "rejected", "posted"]).default("draft").notNull(),
  expenseDate: date("expenseDate"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const approvalRequests = mysqlTable("approvalRequests", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  entityType: varchar("entityType", { length: 64 }).notNull(),
  entityId: int("entityId").notNull(),
  requestedBy: int("requestedBy").notNull(),
  reviewedBy: int("reviewedBy"),
  status: mysqlEnum("status", ["pending", "approved", "rejected"]).default("pending").notNull(),
  note: text("note"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  reviewedAt: timestamp("reviewedAt"),
  approvalStage: varchar("approvalStage", { length: 32 }),
  stageOrder: int("stageOrder"),
});

export const auditLogs = mysqlTable("auditLogs", {
  id: int("id").autoincrement().primaryKey(),
  entityType: varchar("entityType", { length: 64 }).notNull(),
  entityId: int("entityId").notNull(),
  action: varchar("action", { length: 64 }).notNull(),
  actorId: int("actorId").notNull(),
  beforeJson: text("beforeJson"),
  afterJson: text("afterJson"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type UserInvitation = typeof userInvitations.$inferSelect;
export type InsertUserInvitation = typeof userInvitations.$inferInsert;
export type Project = typeof projects.$inferSelect;
export type InsertProject = typeof projects.$inferInsert;
export type Stage = typeof stages.$inferSelect;
export type InsertStage = typeof stages.$inferInsert;
export type Vendor = typeof vendors.$inferSelect;
export type InsertVendor = typeof vendors.$inferInsert;
export type InventoryItem = typeof inventoryItems.$inferSelect;
export type InsertInventoryItem = typeof inventoryItems.$inferInsert;
export type InventoryMovement = typeof inventoryMovements.$inferSelect;
export type ServiceContractEntry = typeof serviceContractEntries.$inferSelect;
export type InsertServiceContractEntry = typeof serviceContractEntries.$inferInsert;
export type LeaveRequest = typeof leaveRequests.$inferSelect;
export type AdvanceRequest = typeof advanceRequests.$inferSelect;
export type InsertInventoryMovement = typeof inventoryMovements.$inferInsert;
export type Employee = typeof employees.$inferSelect;
export type InsertEmployee = typeof employees.$inferInsert;
export type Expense = typeof expenses.$inferSelect;
export type InsertExpense = typeof expenses.$inferInsert;
export type AdministrativePayroll = typeof administrativePayroll.$inferSelect;
export type PayrollAllocation = typeof payrollAllocations.$inferSelect;
export type CustodyMovement = typeof custodyMovements.$inferSelect;
export type InsertCustodyMovement = typeof custodyMovements.$inferInsert;

export const units = mysqlTable("units", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  code: varchar("code", { length: 64 }).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  type: varchar("type", { length: 128 }),
  status: mysqlEnum("status", ["available", "reserved", "sold", "cancelled"]).default("available").notNull(),
  listPrice: decimal("listPrice", { precision: 14, scale: 2 }).default("0").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const sales = mysqlTable("sales", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId").notNull(),
  unitId: int("unitId").notNull(),
  stageId: int("stageId"),
  costItemId: int("costItemId"),
  customerName: varchar("customerName", { length: 255 }).notNull(),
  customerPhone: varchar("customerPhone", { length: 64 }),
  saleDate: date("saleDate"),
  preTaxAmount: decimal("preTaxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  taxAmount: decimal("taxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  recognizedRevenue: decimal("recognizedRevenue", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["draft", "reserved", "confirmed", "cancelled"]).default("draft").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const collections = mysqlTable("collections", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId").notNull(),
  saleId: int("saleId"),
  collectionType: mysqlEnum("collectionType", ["unit_sale", "owner_payment", "contract_payment", "other"]).default("other").notNull(),
  partyName: varchar("partyName", { length: 255 }),
  collectionDestination: mysqlEnum("collectionDestination", ["cash", "bank", "escrow"]).default("cash").notNull(),
  cashAccountId: int("cashAccountId"),
  escrowReference: varchar("escrowReference", { length: 128 }),
  receiptReference: varchar("receiptReference", { length: 128 }),
  collectionDate: date("collectionDate"),
  amount: decimal("amount", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["draft", "received", "reversed"]).default("draft").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const employees = mysqlTable("employees", {
  id: int("id").autoincrement().primaryKey(),
  employeeCode: varchar("employeeCode", { length: 64 }).notNull().unique(),
  employmentType: mysqlEnum("employmentType", ["employee", "worker"]).default("employee").notNull(),
  fullName: varchar("fullName", { length: 255 }).notNull(),
  jobTitle: varchar("jobTitle", { length: 255 }),
  department: varchar("department", { length: 255 }),
  managerName: varchar("managerName", { length: 255 }),
  managerUserId: int("managerUserId"),
  generalManagerUserId: int("generalManagerUserId"),
  phone: varchar("phone", { length: 64 }),
  email: varchar("email", { length: 255 }),
  nationalId: varchar("nationalId", { length: 64 }),
  nationality: varchar("nationality", { length: 128 }),
  birthDate: date("birthDate"),
  hireDate: date("hireDate"),
  workLocation: varchar("workLocation", { length: 255 }),
  address: text("address"),
  nationalAddress: text("nationalAddress"),
  bankName: varchar("bankName", { length: 255 }),
  iban: varchar("iban", { length: 128 }),
  insuranceNumber: varchar("insuranceNumber", { length: 128 }),
  basicSalary: decimal("basicSalary", { precision: 14, scale: 2 }).default("0").notNull(),
  housingAllowance: decimal("housingAllowance", { precision: 14, scale: 2 }).default("0").notNull(),
  transportAllowance: decimal("transportAllowance", { precision: 14, scale: 2 }).default("0").notNull(),
  otherAllowances: decimal("otherAllowances", { precision: 14, scale: 2 }).default("0").notNull(),
  standardDeduction: decimal("standardDeduction", { precision: 14, scale: 2 }).default("0").notNull(),
  notes: text("notes"),
  status: mysqlEnum("status", ["active", "inactive"]).default("active").notNull(),
  defaultProjectId: int("defaultProjectId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const employeeWorkStarts = mysqlTable("employeeWorkStarts", {
  id: int("id").autoincrement().primaryKey(),
  employeeId: int("employeeId").notNull(),
  projectId: int("projectId"),
  workStartDate: date("workStartDate").notNull(),
  jobTitle: varchar("jobTitle", { length: 255 }),
  workLocation: varchar("workLocation", { length: 255 }),
  notes: text("notes"),
  employeeSignatureName: varchar("employeeSignatureName", { length: 255 }).notNull(),
  employeeSignedAt: timestamp("employeeSignedAt").notNull(),
  generalManagerUserId: int("generalManagerUserId"),
  generalManagerSignedAt: timestamp("generalManagerSignedAt"),
  status: mysqlEnum("status", ["pending_general_manager", "signed", "rejected"]).default("pending_general_manager").notNull(),
  rejectionReason: text("rejectionReason"),
  createdBy: int("createdBy").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const payroll = mysqlTable("payroll", {
  id: int("id").autoincrement().primaryKey(),
  payrollRunId: int("payrollRunId"),
  projectId: int("projectId"),
  stageId: int("stageId"),
  employeeId: int("employeeId"),
  employeeName: varchar("employeeName", { length: 255 }).notNull(),
  employeeCode: varchar("employeeCode", { length: 64 }),
  month: int("month").notNull(),
  year: int("year").notNull(),
  classification: mysqlEnum("classification", ["project", "administrative"]).default("project").notNull(),
  allocationRatio: decimal("allocationRatio", { precision: 8, scale: 6 }).default("1").notNull(),
  preTaxAmount: decimal("preTaxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  taxAmount: decimal("taxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  paidAmount: decimal("paidAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  absenceDays: int("absenceDays").default(0).notNull(),
  deductionAmount: decimal("deductionAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  advanceDeductionAmount: decimal("advanceDeductionAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["draft", "pending", "approved", "paid"]).default("draft").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const payrollRuns = mysqlTable("payrollRuns", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  runNumber: varchar("runNumber", { length: 128 }).notNull().unique(),
  month: int("month").notNull(),
  year: int("year").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  paidAmount: decimal("paidAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["draft", "pending", "approved", "rejected", "partially_paid", "paid"]).default("draft").notNull(),
  submittedAt: timestamp("submittedAt"),
  approvedAt: timestamp("approvedAt"),
  approvedBy: int("approvedBy"),
  accrualDocumentId: int("accrualDocumentId"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const payrollSettlements = mysqlTable("payrollSettlements", {
  id: int("id").autoincrement().primaryKey(),
  payrollRunId: int("payrollRunId").notNull(),
  payrollId: int("payrollId").notNull(),
  accountingDocumentId: int("accountingDocumentId").notNull(),
  amount: decimal("amount", { precision: 14, scale: 2 }).notNull().default("0"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const administrativePayroll = mysqlTable("administrativePayroll", {
  id: int("id").autoincrement().primaryKey(),
  employeeName: varchar("employeeName", { length: 255 }).notNull(),
  employeeCode: varchar("employeeCode", { length: 64 }),
  month: int("month").notNull(),
  year: int("year").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  paidAmount: decimal("paidAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["draft", "pending", "approved", "paid"]).default("pending").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const payrollAllocations = mysqlTable("payrollAllocations", {
  id: int("id").autoincrement().primaryKey(),
  administrativePayrollId: int("administrativePayrollId").notNull(),
  projectId: int("projectId").notNull(),
  ratio: decimal("ratio", { precision: 8, scale: 6 }).notNull(),
  allocatedAmount: decimal("allocatedAmount", { precision: 14, scale: 2 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const contractorContracts = mysqlTable("contractorContracts", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  vendorId: int("vendorId").notNull(),
  contractNumber: varchar("contractNumber", { length: 128 }).notNull(),
  description: text("description"),
  contractType: mysqlEnum("contractType", ["building_stage", "supply", "supply_installation", "equipment_rental", "labor_supply"]).default("building_stage").notNull(),
  contractItems: json("contractItems").$type<Array<{ description: string; unit: string; contractedQty: number; unitPrice: number; suppliedQty?: number; installedQty?: number; approvedQty?: number; inventoryItemId?: number; costItemId?: number; accountId?: number }>>(),
  preTaxAmount: decimal("preTaxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  taxRate: decimal("taxRate", { precision: 5, scale: 2 }).default("15").notNull(),
  taxAmount: decimal("taxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["draft", "active", "closed", "cancelled"]).default("active").notNull(),
  contractDate: date("contractDate"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const certificates = mysqlTable("certificates", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  vendorId: int("vendorId"),
  contractId: int("contractId"),
  certificateNumber: varchar("certificateNumber", { length: 128 }).notNull(),
  description: text("description"),
  technicalSpecifications: text("technicalSpecifications"),
  certificateItems: json("certificateItems").$type<Array<{ contractItemIndex: number; suppliedQty?: number; installedQty?: number; approvedQty?: number; unitPrice?: number; inventoryItemId?: number; costItemId?: number; accountId?: number }>>(),
  preTaxAmount: decimal("preTaxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  taxAmount: decimal("taxAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  paidAmount: decimal("paidAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["draft", "pending", "approved", "rejected", "paid"]).default("draft").notNull(),
  certificateDate: date("certificateDate"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const serviceContractEntries = mysqlTable("serviceContractEntries", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  contractId: int("contractId").notNull(),
  vendorId: int("vendorId").notNull(),
  entryType: mysqlEnum("entryType", ["equipment_rental", "labor_supply"]).notNull(),
  serviceDate: date("serviceDate").notNull(),
  periodStart: date("periodStart"),
  periodEnd: date("periodEnd"),
  description: text("description").notNull(),
  equipmentClass: varchar("equipmentClass", { length: 128 }),
  quantity: decimal("quantity", { precision: 14, scale: 3 }).default("1").notNull(),
  rentalDays: decimal("rentalDays", { precision: 14, scale: 3 }).default("0").notNull(),
  dailyRate: decimal("dailyRate", { precision: 14, scale: 2 }).default("0").notNull(),
  workerCategory: varchar("workerCategory", { length: 128 }),
  headcount: decimal("headcount", { precision: 14, scale: 3 }).default("0").notNull(),
  workDays: decimal("workDays", { precision: 14, scale: 3 }).default("0").notNull(),
  dailyWage: decimal("dailyWage", { precision: 14, scale: 2 }).default("0").notNull(),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  expenseId: int("expenseId"),
  status: mysqlEnum("status", ["pending_approval", "posted", "cancelled"]).default("pending_approval").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const custody = mysqlTable("custody", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  holderName: varchar("holderName", { length: 255 }).notNull(),
  issueDate: date("issueDate"),
  issuedAmount: decimal("issuedAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  settledAmount: decimal("settledAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  status: mysqlEnum("status", ["open", "partially_settled", "settled"]).default("open").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const custodyMovements = mysqlTable("custodyMovements", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId"),
  stageId: int("stageId"),
  employeeCode: varchar("employeeCode", { length: 64 }).notNull(),
  employeeId: int("employeeId"),
  employeeName: varchar("employeeName", { length: 255 }).notNull(),
  movementType: mysqlEnum("movementType", ["issue", "spend", "return", "settlement"]).notNull(),
  allocationType: mysqlEnum("allocationType", ["project", "general_cash", "general_admin", "petty_cash", "operating_expense"]).notNull(),
  description: text("description").notNull(),
  amount: decimal("amount", { precision: 14, scale: 2 }).default("0").notNull(),
  signedAmount: decimal("signedAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  movementDate: date("movementDate"),
  expenseType: varchar("expenseType", { length: 64 }),
  vendorId: int("vendorId"),
  payrollBeneficiaryType: mysqlEnum("payrollBeneficiaryType", ["company_employee", "worker"]),
  payrollEmployeeId: int("payrollEmployeeId"),
  payrollBeneficiaryName: varchar("payrollBeneficiaryName", { length: 255 }),
  paymentVoucherId: int("paymentVoucherId"),
  linkedExpenseId: int("linkedExpenseId"),
  allocationRatio: decimal("allocationRatio", { precision: 5, scale: 2 }).default("100"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const attendance = mysqlTable("attendance", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  employeeCode: varchar("employeeCode", { length: 64 }),
  employeeId: int("employeeId"),
  employeeName: varchar("employeeName", { length: 255 }).notNull(),
  attendanceDate: date("attendanceDate").notNull(),
  checkIn: varchar("checkIn", { length: 16 }),
  checkOut: varchar("checkOut", { length: 16 }),
  status: mysqlEnum("status", ["present", "absent", "late", "leave"]).default("present").notNull(),
  source: mysqlEnum("source", ["manual", "biometric", "mobile_location", "import"]).default("manual").notNull(),
  latitude: decimal("latitude", { precision: 10, scale: 7 }),
  longitude: decimal("longitude", { precision: 10, scale: 7 }),
  locationAccuracyMeters: decimal("locationAccuracyMeters", { precision: 10, scale: 2 }),
  locationDistanceMeters: decimal("locationDistanceMeters", { precision: 10, scale: 2 }),
  locationMatchStatus: mysqlEnum("locationMatchStatus", ["not_checked", "within_range", "outside_range", "no_site_configured"]).default("not_checked").notNull(),
  locationCapturedAt: timestamp("locationCapturedAt"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const attachments = mysqlTable("attachments", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  entityType: varchar("entityType", { length: 64 }).notNull(),
  entityId: int("entityId").notNull(),
  documentType: varchar("documentType", { length: 128 }).notNull(),
  fileName: varchar("fileName", { length: 255 }).notNull(),
  fileUrl: text("fileUrl").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const notifications = mysqlTable("notifications", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  type: varchar("type", { length: 64 }).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  message: text("message").notNull(),
  readAt: timestamp("readAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const complianceDocuments = mysqlTable("complianceDocuments", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  employeeId: int("employeeId"),
  documentScope: mysqlEnum("documentScope", ["company", "employee"]).notNull(),
  documentType: varchar("documentType", { length: 128 }).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  referenceNumber: varchar("referenceNumber", { length: 128 }),
  issuingAuthority: varchar("issuingAuthority", { length: 255 }),
  issuedDate: date("issuedDate"),
  expiryDate: date("expiryDate").notNull(),
  reminderDays: int("reminderDays").notNull().default(30),
  attachmentUrl: text("attachmentUrl"),
  attachmentName: varchar("attachmentName", { length: 255 }),
  status: mysqlEnum("status", ["active", "archived"]).notNull().default("active"),
  lastAlertKey: varchar("lastAlertKey", { length: 128 }),
  lastAlertAt: timestamp("lastAlertAt"),
  createdBy: int("createdBy").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const dailyTasks = mysqlTable("dailyTasks", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  assignedEmployeeId: int("assignedEmployeeId"),
  assignedEmployeeIds: text("assignedEmployeeIds"),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  dueDate: timestamp("dueDate"),
  startDate: timestamp("startDate"),
  endDate: timestamp("endDate"),
  progress: int("progress").notNull().default(0),
  priority: varchar("priority", { length: 16 }).notNull().default("normal"),
  status: varchar("status", { length: 16 }).notNull().default("open"),
  createdBy: int("createdBy"),
  completedAt: timestamp("completedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const leaveRequests = mysqlTable("leaveRequests", {
  id: int("id").autoincrement().primaryKey(),
  requestedBy: int("requestedBy").notNull(),
  employeeId: int("employeeId"),
  leaveType: mysqlEnum("leaveType", ["annual", "sick", "emergency", "unpaid", "official", "other"]).default("annual").notNull(),
  startDate: date("startDate").notNull(),
  endDate: date("endDate").notNull(),
  days: decimal("days", { precision: 8, scale: 2 }).default("0").notNull(),
  reason: text("reason"),
  status: mysqlEnum("status", ["pending", "approved", "rejected", "cancelled"]).default("pending").notNull(),
  reviewedBy: int("reviewedBy"),
  reviewedAt: timestamp("reviewedAt"),
  rejectionReason: text("rejectionReason"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export const advanceRequests = mysqlTable("advanceRequests", {
  id: int("id").autoincrement().primaryKey(),
  requestedBy: int("requestedBy").notNull(),
  employeeId: int("employeeId"),
  amount: decimal("amount", { precision: 14, scale: 2 }).notNull(),
  reason: text("reason").notNull(),
  repaymentDate: date("repaymentDate"),
  repaymentMode: mysqlEnum("repaymentMode", ["single", "installments"]).default("single").notNull(),
  repaymentStartMonth: int("repaymentStartMonth"),
  repaymentStartYear: int("repaymentStartYear"),
  installmentCount: int("installmentCount").default(1).notNull(),
  status: mysqlEnum("status", ["pending", "approved", "rejected", "cancelled"]).default("pending").notNull(),
  reviewedBy: int("reviewedBy"),
  reviewedAt: timestamp("reviewedAt"),
  rejectionReason: text("rejectionReason"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const advanceRepayments = mysqlTable("advanceRepayments", {
  id: int("id").autoincrement().primaryKey(),
  advanceRequestId: int("advanceRequestId").notNull(),
  employeeId: int("employeeId").notNull(),
  scheduledMonth: int("scheduledMonth").notNull(),
  scheduledYear: int("scheduledYear").notNull(),
  scheduledAmount: decimal("scheduledAmount", { precision: 14, scale: 2 }).notNull(),
  appliedAmount: decimal("appliedAmount", { precision: 14, scale: 2 }).default("0").notNull(),
  payrollRunId: int("payrollRunId"),
  payrollId: int("payrollId"),
  status: mysqlEnum("status", ["scheduled", "reserved", "applied", "deferred", "cancelled"]).default("scheduled").notNull(),
  deferredAt: timestamp("deferredAt"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export const periodLocks = mysqlTable("periodLocks", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  periodYear: int("periodYear").notNull(),
  periodMonth: int("periodMonth").notNull(),
  lockedBy: int("lockedBy").notNull(),
  lockedAt: timestamp("lockedAt").defaultNow().notNull(),
  reason: text("reason"),
});

export const materialRequisitions = mysqlTable("materialRequisitions", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  requestedBy: int("requestedBy").notNull(),
  requestNumber: varchar("requestNumber", { length: 128 }).notNull().unique(),
  description: text("description"),
  status: mysqlEnum("status", ["draft", "pending_approval", "approved", "rejected", "converted", "cancelled"]).default("draft").notNull(),
  requiredBy: date("requiredBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const materialRequisitionItems = mysqlTable("materialRequisitionItems", {
  id: int("id").autoincrement().primaryKey(),
  requisitionId: int("requisitionId").notNull(),
  inventoryItemId: int("inventoryItemId"),
  costItemId: int("costItemId"),
  contractId: int("contractId"),
  contractItemIndex: int("contractItemIndex"),
  description: varchar("description", { length: 255 }).notNull(),
  unit: varchar("unit", { length: 64 }),
  quantity: decimal("quantity", { precision: 14, scale: 3 }).notNull().default("1"),
  estimatedUnitCost: decimal("estimatedUnitCost", { precision: 14, scale: 2 }).notNull().default("0"),
  planningStatus: mysqlEnum("planningStatus", ["within_plan", "over_plan", "unplanned"]).notNull().default("unplanned"),
  plannedQuantity: decimal("plannedQuantity", { precision: 14, scale: 3 }).notNull().default("0"),
  notes: text("notes"),
});

export const purchaseOrders = mysqlTable("purchaseOrders", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  vendorId: int("vendorId").notNull(),
  requisitionId: int("requisitionId"),
  orderNumber: varchar("orderNumber", { length: 128 }).notNull().unique(),
  status: mysqlEnum("status", ["draft", "pending_approval", "approved", "partially_received", "received", "cancelled"]).default("draft").notNull(),
  invoiceNumber: varchar("invoiceNumber", { length: 128 }),
  invoiceStatus: mysqlEnum("invoiceStatus", ["not_received", "received", "partially_paid", "paid"]).default("not_received").notNull(),
  invoicedAmount: decimal("invoicedAmount", { precision: 14, scale: 2 }).notNull().default("0"),
  paidAmount: decimal("paidAmount", { precision: 14, scale: 2 }).notNull().default("0"),
  subtotal: decimal("subtotal", { precision: 14, scale: 2 }).notNull().default("0"),
  taxAmount: decimal("taxAmount", { precision: 14, scale: 2 }).notNull().default("0"),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).notNull().default("0"),
  orderDate: date("orderDate"),
  expectedDate: date("expectedDate"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const purchaseOrderItems = mysqlTable("purchaseOrderItems", {
  id: int("id").autoincrement().primaryKey(),
  purchaseOrderId: int("purchaseOrderId").notNull(),
  inventoryItemId: int("inventoryItemId"),
  costItemId: int("costItemId"),
  description: varchar("description", { length: 255 }).notNull(),
  unit: varchar("unit", { length: 64 }),
  quantity: decimal("quantity", { precision: 14, scale: 3 }).notNull().default("1"),
  unitCost: decimal("unitCost", { precision: 14, scale: 2 }).notNull().default("0"),
  receivedQuantity: decimal("receivedQuantity", { precision: 14, scale: 3 }).notNull().default("0"),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).notNull().default("0"),
});

export const purchaseReceipts = mysqlTable("purchaseReceipts", {
  id: int("id").autoincrement().primaryKey(),
  purchaseOrderId: int("purchaseOrderId").notNull(),
  projectId: int("projectId").notNull(),
  stageId: int("stageId"),
  receiptNumber: varchar("receiptNumber", { length: 128 }).notNull().unique(),
  receivedDate: date("receivedDate"),
  notes: text("notes"),
  status: mysqlEnum("status", ["draft", "posted", "cancelled"]).default("draft").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const purchaseReceiptItems = mysqlTable("purchaseReceiptItems", {
  id: int("id").autoincrement().primaryKey(),
  receiptId: int("receiptId").notNull(),
  purchaseOrderItemId: int("purchaseOrderItemId").notNull(),
  quantity: decimal("quantity", { precision: 14, scale: 3 }).notNull().default("0"),
});

export const approvalPolicies = mysqlTable("approvalPolicies", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  entityType: varchar("entityType", { length: 32 }).notNull(),
  thresholdAmount: decimal("thresholdAmount", { precision: 14, scale: 2 }).notNull().default("0"),
  createdBy: int("createdBy").notNull(),
  updatedBy: int("updatedBy").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});


export const companyProfiles = mysqlTable("companyProfiles", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  legalName: varchar("legalName", { length: 255 }).notNull(),
  tradeName: varchar("tradeName", { length: 255 }),
  commercialRegistration: varchar("commercialRegistration", { length: 128 }),
  taxNumber: varchar("taxNumber", { length: 128 }),
  nationalAddress: text("nationalAddress"),
  phone: varchar("phone", { length: 64 }),
  email: varchar("email", { length: 255 }),
  website: varchar("website", { length: 255 }),
  logoUrl: text("logoUrl"),
  notes: text("notes"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const cashAccounts = mysqlTable("cashAccounts", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  code: varchar("code", { length: 32 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  accountType: mysqlEnum("accountType", ["bank", "cash"]).notNull(),
  bankName: varchar("bankName", { length: 255 }),
  accountNumber: varchar("accountNumber", { length: 128 }),
  iban: varchar("iban", { length: 64 }),
  currency: varchar("currency", { length: 8 }).notNull().default("SAR"),
  accountId: int("accountId"),
  openingBalance: decimal("openingBalance", { precision: 14, scale: 2 }).notNull().default("0"),
  isActive: int("isActive").notNull().default(1),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const accounts = mysqlTable("accounts", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  code: varchar("code", { length: 32 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  accountType: mysqlEnum("accountType", ["asset", "liability", "equity", "revenue", "expense"]).notNull(),
  parentId: int("parentId"),
  isPostable: int("isPostable").notNull().default(1),
  isActive: int("isActive").notNull().default(1),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const accountingDocuments = mysqlTable("accountingDocuments", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId"),
  documentType: mysqlEnum("documentType", ["sales_invoice", "purchase_invoice", "purchase_receipt", "credit_note", "journal_entry", "payment_voucher", "receipt_voucher", "quotation", "purchase_order"]).notNull(),
  documentNumber: varchar("documentNumber", { length: 128 }).notNull().unique(),
  partyName: varchar("partyName", { length: 255 }),
  partyTaxNumber: varchar("partyTaxNumber", { length: 64 }),
  voucherCategory: mysqlEnum("voucherCategory", ["contractor", "supplier", "materials", "payroll", "operating", "administrative", "petty_cash"]),
  contractorId: int("contractorId"),
  supplierId: int("supplierId"),
  purchaseInvoiceId: int("purchaseInvoiceId"),
  relatedDocumentType: varchar("relatedDocumentType", { length: 64 }),
  relatedDocumentId: int("relatedDocumentId"),
  originalDocumentId: int("originalDocumentId"),
  sourceDocumentId: int("sourceDocumentId"),
  returnType: mysqlEnum("returnType", ["full", "partial"]),
  settlementType: mysqlEnum("settlementType", ["invoice", "direct"]),
  certificateId: int("certificateId"),
  documentDate: date("documentDate"),
  dueDate: date("dueDate"),
  sourceAccountId: int("sourceAccountId"),
  amount: decimal("amount", { precision: 14, scale: 2 }).notNull().default("0"),
  taxAmount: decimal("taxAmount", { precision: 14, scale: 2 }).notNull().default("0"),
  totalAmount: decimal("totalAmount", { precision: 14, scale: 2 }).notNull().default("0"),
  paidAmount: decimal("paidAmount", { precision: 14, scale: 2 }).notNull().default("0"),
  paymentStatus: mysqlEnum("paymentStatus", ["unpaid", "partially_paid", "paid"]).notNull().default("unpaid"),
  paymentMethod: mysqlEnum("paymentMethod", ["cash", "bank"]),
  status: mysqlEnum("status", ["draft", "posted", "cancelled"]).notNull().default("draft"),
  notes: text("notes"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const costItems = mysqlTable("costItems", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  parentId: int("parentId"),
  code: varchar("code", { length: 32 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  category: varchar("category", { length: 64 }).notNull().default("materials"),
  accountId: int("accountId"),
  isActive: int("isActive").notNull().default(1),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const estimates = mysqlTable("estimates", {
  id: int("id").autoincrement().primaryKey(),
  companyId: int("companyId"),
  projectId: int("projectId"),
  contractId: int("contractId"),
  certificateId: int("certificateId"),
  code: varchar("code", { length: 64 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  estimateType: mysqlEnum("estimateType", ["contracting", "development", "general"]).notNull().default("contracting"),
  status: mysqlEnum("status", ["draft", "submitted", "approved", "archived"]).notNull().default("draft"),
  version: int("version").notNull().default(1),
  clientName: varchar("clientName", { length: 255 }),
  siteLocation: varchar("siteLocation", { length: 255 }),
  notes: text("notes"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const estimateLines = mysqlTable("estimateLines", {
  id: int("id").autoincrement().primaryKey(),
  estimateId: int("estimateId").notNull(),
  parentId: int("parentId"),
  costItemId: int("costItemId"),
  itemCode: varchar("itemCode", { length: 64 }),
  category: varchar("category", { length: 128 }).notNull().default("أعمال عامة"),
  description: text("description").notNull(),
  unit: varchar("unit", { length: 64 }).notNull().default("مقطوعية"),
  quantity: decimal("quantity", { precision: 14, scale: 3 }).notNull().default("1"),
  materialCost: decimal("materialCost", { precision: 14, scale: 2 }).notNull().default("0"),
  laborCost: decimal("laborCost", { precision: 14, scale: 2 }).notNull().default("0"),
  equipmentCost: decimal("equipmentCost", { precision: 14, scale: 2 }).notNull().default("0"),
  otherCost: decimal("otherCost", { precision: 14, scale: 2 }).notNull().default("0"),
  unitRate: decimal("unitRate", { precision: 14, scale: 2 }).notNull().default("0"),
  totalCost: decimal("totalCost", { precision: 14, scale: 2 }).notNull().default("0"),
  alternativeGroup: varchar("alternativeGroup", { length: 128 }),
  isAlternative: int("isAlternative").notNull().default(0),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const accountingDocumentLines = mysqlTable("accountingDocumentLines", {
  id: int("id").autoincrement().primaryKey(),
  documentId: int("documentId").notNull(),
  accountId: int("accountId").notNull(),
  costItemId: int("costItemId"),
  projectId: int("projectId"),
  stageId: int("stageId"),
  description: text("description"),
  debit: decimal("debit", { precision: 14, scale: 2 }).notNull().default("0"),
  credit: decimal("credit", { precision: 14, scale: 2 }).notNull().default("0"),
});


export const fixedAssets = mysqlTable("fixedAssets", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  assetCode: varchar("assetCode", { length: 64 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  category: varchar("category", { length: 128 }).notNull().default("معدات وأصول تشغيلية"),
  acquisitionDate: date("acquisitionDate").notNull(),
  inServiceDate: date("inServiceDate").notNull(),
  acquisitionCost: decimal("acquisitionCost", { precision: 14, scale: 2 }).notNull(),
  residualValue: decimal("residualValue", { precision: 14, scale: 2 }).notNull().default("0"),
  usefulLifeMonths: int("usefulLifeMonths").notNull(),
  depreciationMethod: mysqlEnum("depreciationMethod", ["straight_line"]).notNull().default("straight_line"),
  assetAccountId: int("assetAccountId").notNull(),
  depreciationExpenseAccountId: int("depreciationExpenseAccountId").notNull(),
  accumulatedDepreciationAccountId: int("accumulatedDepreciationAccountId").notNull(),
  sourceDocumentId: int("sourceDocumentId"),
  status: mysqlEnum("status", ["active", "disposed"]).notNull().default("active"),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const fixedAssetDepreciation = mysqlTable("fixedAssetDepreciation", {
  id: int("id").autoincrement().primaryKey(),
  assetId: int("assetId").notNull(),
  periodStart: date("periodStart").notNull(),
  periodEnd: date("periodEnd").notNull(),
  depreciationAmount: decimal("depreciationAmount", { precision: 14, scale: 2 }).notNull(),
  accumulatedAmount: decimal("accumulatedAmount", { precision: 14, scale: 2 }).notNull(),
  netBookValue: decimal("netBookValue", { precision: 14, scale: 2 }).notNull(),
  journalDocumentId: int("journalDocumentId"),
  status: mysqlEnum("status", ["planned", "posted"]).notNull().default("planned"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
