import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, Clock3, FileCheck2, XCircle } from "lucide-react";
import { useLocation } from "wouter";

export default function Approvals() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const { data: approvals = [], isLoading } = trpc.erp.approvals.list.useQuery();
  const decide = trpc.erp.approvals.decide.useMutation({ onSuccess: () => utils.erp.approvals.list.invalidate() });
  const decideInventory = trpc.erp.inventory.movements.decide.useMutation({ onSuccess: () => utils.erp.approvals.list.invalidate() });
  return <DashboardLayout><div dir="rtl" className="min-h-screen bg-[#f7f8fa] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-6xl space-y-6"><header><Button variant="ghost" className="mb-2 gap-2 px-0 text-slate-500" onClick={() => setLocation("/")}><ArrowRight className="h-4 w-4" /> العودة للوحة التنفيذ</Button><h1 className="text-3xl font-bold text-[#18324b]">الموافقات والمستندات</h1><p className="mt-2 text-sm text-slate-500">لا تنتقل المعاملة إلى التقارير النهائية إلا بعد المرور بدورة الاعتماد المناسبة.</p></header><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg text-[#18324b]"><FileCheck2 className="h-5 w-5 text-[#b28a3b]" /> صندوق الموافقات</CardTitle></CardHeader><CardContent className="space-y-3">{isLoading ? <div className="py-12 text-center text-sm text-slate-500">جارٍ تحميل الطلبات...</div> : approvals.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50 py-14 text-center"><Clock3 className="mx-auto h-9 w-9 text-[#b28a3b]" /><p className="mt-3 font-semibold text-[#18324b]">لا توجد طلبات موافقة حاليًا</p><p className="mt-1 text-sm text-slate-500">ستظهر هنا المصروفات والرواتب والمستخلصات عند إرسالها للمراجعة.</p></div> : approvals.map((approval) => <div key={approval.id} className="flex flex-col gap-4 rounded-2xl border border-slate-100 bg-white p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><div className="rounded-xl bg-amber-50 p-2 text-amber-700"><Clock3 className="h-5 w-5" /></div><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-[#18324b]">طلب {approval.entityType} #{approval.entityId}</p><Badge variant="outline">{approval.status}</Badge></div><p className="mt-1 text-xs text-slate-500">أنشأه المستخدم #{approval.requestedBy} · {approval.note || "بدون ملاحظة"}</p></div></div>{approval.status === "pending" && <div className="flex gap-2"><Button disabled={decide.isPending || decideInventory.isPending} onClick={() => approval.entityType === "inventoryMovement" ? decideInventory.mutate({ id: approval.entityId, decision: "approved" }) : decide.mutate({ id: approval.id, decision: "approved" })} className="gap-2 bg-emerald-600 hover:bg-emerald-700"><CheckCircle2 className="h-4 w-4" /> اعتماد</Button><Button disabled={decide.isPending || decideInventory.isPending} variant="outline" onClick={() => approval.entityType === "inventoryMovement" ? decideInventory.mutate({ id: approval.entityId, decision: "rejected" }) : decide.mutate({ id: approval.id, decision: "rejected" })} className="gap-2 border-rose-200 text-rose-700 hover:bg-rose-50"><XCircle className="h-4 w-4" /> رفض</Button></div>}</div>)}</CardContent></Card></div></div></DashboardLayout>;
}
