import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, CheckCircle2, Database, ExternalLink, ShieldAlert } from "lucide-react";
import { useLocation } from "wouter";

const severityLabel = { critical: "حرج", warning: "يحتاج مراجعة", info: "معلومة" } as const;
const severityClass = { critical: "bg-rose-50 text-rose-700 border-rose-200", warning: "bg-amber-50 text-amber-700 border-amber-200", info: "bg-sky-50 text-sky-700 border-sky-200" } as const;

export default function DataQuality() {
  const [, setLocation] = useLocation();
  const { data, isLoading, refetch } = trpc.erp.reports.dataQuality.useQuery();
  const issues = data?.issues ?? [];
  return <DashboardLayout><div dir="rtl" className="min-h-screen bg-[#f7f8fa] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl space-y-6">
    <header><Button variant="ghost" className="mb-2 gap-2 px-0 text-slate-500" onClick={() => setLocation("/")}><ArrowRight className="h-4 w-4" /> العودة للوحة التنفيذ</Button><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#b28a3b]">حوكمة النظام</p><h1 className="text-3xl font-bold text-[#18324b]">مركز جودة البيانات</h1><p className="mt-2 text-sm text-slate-500">فحص استباقي للحقول الناقصة والتعارضات التي قد تؤثر على التقارير والقرارات المالية.</p></div><Button variant="outline" onClick={() => refetch()}><Database className="ml-2 h-4 w-4" />إعادة الفحص</Button></div></header>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="درجة الجودة" value={isLoading ? "—" : `${data?.score ?? 100}%`} tone={(data?.score ?? 100) >= 90 ? "good" : "warn"} /><Metric label="أخطاء حرجة" value={String(data?.totals.critical ?? 0)} tone="danger" /><Metric label="ملاحظات مراجعة" value={String(data?.totals.warning ?? 0)} tone="warn" /><Metric label="إجمالي التنبيهات" value={String(issues.length)} tone="neutral" /></section>
    <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg text-[#18324b]"><ShieldAlert className="h-5 w-5 text-[#b28a3b]" />قائمة الإجراءات المطلوبة</CardTitle><p className="text-sm text-slate-500">ابدأ بالعناصر الحرجة، ثم استكمل التنبيهات قبل إقفال الفترة أو اعتماد التقرير.</p></CardHeader><CardContent>{isLoading ? <p className="py-12 text-center text-sm text-slate-500">جارٍ فحص البيانات...</p> : issues.length ? <div className="space-y-3">{issues.map((issue) => <div key={issue.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-100 bg-white p-4"><div className="flex min-w-0 items-start gap-3"><div className={`mt-0.5 rounded-full p-2 ${issue.severity === "critical" ? "bg-rose-100 text-rose-700" : issue.severity === "warning" ? "bg-amber-100 text-amber-700" : "bg-sky-100 text-sky-700"}`}>{issue.severity === "critical" ? <AlertTriangle className="h-4 w-4" /> : <Database className="h-4 w-4" />}</div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-[#18324b]">{issue.title}</h3><Badge variant="outline" className={severityClass[issue.severity]}>{severityLabel[issue.severity]}</Badge></div><p className="mt-1 text-sm text-slate-600">{issue.detail}</p><p className="mt-1 text-xs text-slate-400">السجل: {issue.entityType} #{issue.entityId}</p></div></div><Button variant="outline" size="sm" onClick={() => setLocation(issue.entityType === "project" || issue.entityType === "stage" ? "/projects" : issue.entityType === "vendor" ? "/operations?tab=vendors" : "/employees")}>{issue.action}<ExternalLink className="mr-2 h-3.5 w-3.5" /></Button></div>)}</div> : <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center text-emerald-800"><CheckCircle2 className="mx-auto h-9 w-9" /><p className="mt-3 font-bold">لا توجد ملاحظات جودة بيانات حاليًا</p><p className="mt-1 text-sm">الملفات الأساسية جاهزة للمراجعة التشغيلية.</p></div>}</CardContent></Card>
  </div></div></DashboardLayout>;
}
function Metric({ label, value, tone }: { label: string; value: string; tone: "good" | "warn" | "danger" | "neutral" }) { const styles = { good: "border-emerald-200 bg-emerald-50 text-emerald-800", warn: "border-amber-200 bg-amber-50 text-amber-800", danger: "border-rose-200 bg-rose-50 text-rose-800", neutral: "border-slate-200 bg-white text-[#18324b]" }; return <Card className={`border shadow-sm ${styles[tone]}`}><CardContent className="p-5"><p className="text-sm opacity-75">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></CardContent></Card>; }
