import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { ArrowRight, Calculator, ClipboardList, Eye, Plus, Save, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";

const money = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });
type Line = { itemCode: string; category: string; description: string; unit: string; quantity: string; materialCost: string; laborCost: string; equipmentCost: string; otherCost: string; unitRate: string; costItemId: string; alternativeGroup: string; isAlternative: boolean; notes: string };
const blankLine = (): Line => ({ itemCode: "", category: "أعمال عامة", description: "", unit: "مقطوعية", quantity: "1", materialCost: "0", laborCost: "0", equipmentCost: "0", otherCost: "0", unitRate: "0", costItemId: "", alternativeGroup: "", isAlternative: false, notes: "" });

export default function Estimates() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const [search, setSearch] = useState("");
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState({ code: "", name: "", projectId: "", contractId: "", certificateId: "", estimateType: "contracting" as "contracting" | "development" | "general", status: "draft" as "draft" | "submitted", version: "1", clientName: "", siteLocation: "", notes: "" });
  const [lines, setLines] = useState<Line[]>([blankLine()]);
  const projects = trpc.erp.projects.list.useQuery();
  const costItems = trpc.erp.costItems.list.useQuery({ projectId: form.projectId ? Number(form.projectId) : undefined });
  const linkedRecords = trpc.erp.estimates.linkedRecords.useQuery({ projectId: form.projectId ? Number(form.projectId) : undefined });
  const estimates = trpc.erp.estimates.list.useQuery({ search: search || undefined });
  const create = trpc.erp.estimates.create.useMutation({ onSuccess: () => { utils.erp.estimates.list.invalidate(); setForm({ code: "", name: "", projectId: "", contractId: "", certificateId: "", estimateType: "contracting", status: "draft", version: "1", clientName: "", siteLocation: "", notes: "" }); setLines([blankLine()]); } });
  const deleteEstimate = trpc.erp.estimates.delete.useMutation({ onSuccess: () => utils.erp.estimates.list.invalidate() });
  const estimateDetails = trpc.erp.estimates.get.useQuery({ id: editingId ?? 0 }, { enabled: Boolean(editingId) });
  const update = trpc.erp.estimates.update.useMutation({ onSuccess: () => { utils.erp.estimates.list.invalidate(); setEditingId(null); setForm({ code: "", name: "", projectId: "", contractId: "", certificateId: "", estimateType: "contracting", status: "draft", version: "1", clientName: "", siteLocation: "", notes: "" }); setLines([blankLine()]); } });
  useEffect(() => { if (!estimateDetails.data) return; const item = estimateDetails.data.estimate; setForm({ code: item.code, name: item.name, projectId: item.projectId ? String(item.projectId) : "", contractId: item.contractId ? String(item.contractId) : "", certificateId: item.certificateId ? String(item.certificateId) : "", estimateType: item.estimateType, status: item.status === "submitted" ? "submitted" : "draft", version: String(item.version), clientName: item.clientName || "", siteLocation: item.siteLocation || "", notes: item.notes || "" }); setLines(estimateDetails.data.lines.map((line) => ({ itemCode: line.itemCode || "", category: line.category, description: line.description, unit: line.unit, quantity: String(line.quantity), materialCost: String(line.materialCost), laborCost: String(line.laborCost), equipmentCost: String(line.equipmentCost), otherCost: String(line.otherCost), unitRate: String(line.unitRate), costItemId: line.costItemId ? String(line.costItemId) : "", alternativeGroup: line.alternativeGroup || "", isAlternative: Boolean(line.isAlternative), notes: line.notes || "" }))); }, [estimateDetails.data]);
  const totals = useMemo(() => lines.reduce((sum, line) => { const rate = Number(line.unitRate) || Number(line.materialCost) + Number(line.laborCost) + Number(line.equipmentCost) + Number(line.otherCost); return sum + (Number(line.quantity) || 0) * rate; }, 0), [lines]);
  const updateLine = (index: number, key: keyof Line, value: string | boolean) => setLines((current) => current.map((line, i) => i === index ? { ...line, [key]: value } : line));
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.code.trim() || !form.name.trim() || !lines.some((line) => line.description.trim())) return; const payload = { code: form.code.trim(), name: form.name.trim(), projectId: form.projectId ? Number(form.projectId) : null, contractId: form.contractId ? Number(form.contractId) : null, certificateId: form.certificateId ? Number(form.certificateId) : null, estimateType: form.estimateType, status: form.status, version: Number(form.version || 1), clientName: form.clientName || undefined, siteLocation: form.siteLocation || undefined, notes: form.notes || undefined, lines: lines.filter((line) => line.description.trim()).map((line) => ({ itemCode: line.itemCode || undefined, category: line.category, description: line.description, unit: line.unit, quantity: Number(line.quantity || 0), materialCost: Number(line.materialCost || 0), laborCost: Number(line.laborCost || 0), equipmentCost: Number(line.equipmentCost || 0), otherCost: Number(line.otherCost || 0), unitRate: Number(line.unitRate || 0), costItemId: line.costItemId ? Number(line.costItemId) : null, alternativeGroup: line.alternativeGroup || undefined, isAlternative: line.isAlternative, notes: line.notes || undefined })) }; if (editingId) update.mutate({ id: editingId, ...payload }); else create.mutate({ code: form.code.trim(), name: form.name.trim(), projectId: form.projectId ? Number(form.projectId) : null, contractId: form.contractId ? Number(form.contractId) : null, certificateId: form.certificateId ? Number(form.certificateId) : null, estimateType: form.estimateType, status: form.status, version: Number(form.version || 1), clientName: form.clientName || undefined, siteLocation: form.siteLocation || undefined, notes: form.notes || undefined, lines: lines.filter((line) => line.description.trim()).map((line) => ({ itemCode: line.itemCode || undefined, category: line.category, description: line.description, unit: line.unit, quantity: Number(line.quantity || 0), materialCost: Number(line.materialCost || 0), laborCost: Number(line.laborCost || 0), equipmentCost: Number(line.equipmentCost || 0), otherCost: Number(line.otherCost || 0), unitRate: Number(line.unitRate || 0), costItemId: line.costItemId ? Number(line.costItemId) : null, alternativeGroup: line.alternativeGroup || undefined, isAlternative: line.isAlternative, notes: line.notes || undefined })) }); };
  return <div dir="rtl" className="min-h-screen bg-[#f7f8fa] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><Button variant="ghost" className="mb-2 gap-2 px-0 text-slate-500" onClick={() => setLocation("/")}><ArrowRight className="h-4 w-4" /> العودة للوحة التنفيذ</Button><p className="text-sm font-semibold text-[#b28a3b]">التسعير والتخطيط</p><h1 className="mt-1 text-3xl font-bold text-[#18324b]">المقايسات التفصيلية</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-500">أنشئ مقايسة مستقلة لأعمال المقاولات أو التطوير، واربطها بالمشروع وبند التكلفة عند الحاجة فقط. حفظ المقايسة لا ينشئ فاتورة أو سندًا أو حركة مالية تلقائيًا.</p></div><Badge className="bg-[#18324b] px-4 py-2">{estimates.data?.length ?? 0} مقايسة محفوظة</Badge></header>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.7fr)]"><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-[#18324b]"><Calculator className="h-5 w-5 text-[#b28a3b]" /> {editingId ? "تعديل المقايسة" : "إنشاء مقايسة جديدة"}</CardTitle><p className="text-xs leading-6 text-slate-500">الربط بالمشروع اختياري، ويمكن حفظ المقايسة كمسودة ثم مراجعتها قبل اعتمادها.</p></CardHeader><CardContent><form onSubmit={submit} className="space-y-5">
      <div className="grid gap-3 md:grid-cols-4"><Field label="كود المقايسة *" value={form.code} onChange={(v) => setForm({ ...form, code: v })} placeholder="EST-001" /><Field label="اسم المقايسة *" value={form.name} onChange={(v) => setForm({ ...form, name: v })} placeholder="مقايسة أعمال الهيكل" /><Field label="اسم المالك / العميل" value={form.clientName} onChange={(v) => setForm({ ...form, clientName: v })} /><Field label="الموقع" value={form.siteLocation} onChange={(v) => setForm({ ...form, siteLocation: v })} /></div>
      <div className="grid gap-3 md:grid-cols-4"><SelectField label="نوع المقايسة" value={form.estimateType} onChange={(v) => setForm({ ...form, estimateType: v as typeof form.estimateType })} options={[{ value: "contracting", label: "مقاولات" }, { value: "development", label: "تطوير عقاري" }, { value: "general", label: "عامة" }]} /><SelectField label="المشروع — اختياري" value={form.projectId} onChange={(v) => setForm({ ...form, projectId: v })} options={[{ value: "", label: "مقايسة مستقلة بلا مشروع" }, ...(projects.data ?? []).map((project) => ({ value: String(project.id), label: `${project.code} — ${project.name}` }))]} /><SelectField label="حالة الحفظ" value={form.status} onChange={(v) => setForm({ ...form, status: v as typeof form.status })} options={[{ value: "draft", label: "مسودة" }, { value: "submitted", label: "جاهزة للمراجعة" }]} /><SelectField label="العقد — اختياري" value={form.contractId} onChange={(v) => setForm({ ...form, contractId: v })} options={[{ value: "", label: "بدون عقد" }, ...(linkedRecords.data?.contracts ?? []).map((contract) => ({ value: String(contract.id), label: `${contract.contractNumber} — ${contract.description || "عقد مقاولات"}` }))]} /><SelectField label="المستخلص — اختياري" value={form.certificateId} onChange={(v) => setForm({ ...form, certificateId: v })} options={[{ value: "", label: "بدون مستخلص" }, ...(linkedRecords.data?.certificates ?? []).map((certificate) => ({ value: String(certificate.id), label: `${certificate.certificateNumber} — ${certificate.description || "مستخلص"}` }))]} /><Field label="رقم الإصدار" type="number" value={form.version} onChange={(v) => setForm({ ...form, version: v })} /></div>
      <div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[1250px] text-right text-sm"><thead className="bg-[#18324b] text-white"><tr><th className="p-3">البند</th><th className="p-3">التصنيف</th><th className="p-3">الوصف *</th><th className="p-3">الوحدة</th><th className="p-3">الكمية</th><th className="p-3">خامات</th><th className="p-3">عمالة</th><th className="p-3">معدات</th><th className="p-3">أخرى</th><th className="p-3">سعر الوحدة</th><th className="p-3">بند التكلفة</th><th className="p-3">الإجمالي</th><th className="p-3"></th></tr></thead><tbody>{lines.map((line, index) => { const rate = Number(line.unitRate) || Number(line.materialCost) + Number(line.laborCost) + Number(line.equipmentCost) + Number(line.otherCost); return <tr key={index} className="border-b border-slate-100 align-top"><td className="p-2"><Cell value={line.itemCode} onChange={(v) => updateLine(index, "itemCode", v)} placeholder="01.01" /></td><td className="p-2"><Cell value={line.category} onChange={(v) => updateLine(index, "category", v)} /></td><td className="p-2 min-w-[220px]"><Cell value={line.description} onChange={(v) => updateLine(index, "description", v)} placeholder="وصف الأعمال" /></td><td className="p-2"><Cell value={line.unit} onChange={(v) => updateLine(index, "unit", v)} /></td><td className="p-2"><Cell type="number" value={line.quantity} onChange={(v) => updateLine(index, "quantity", v)} /></td><td className="p-2"><Cell type="number" value={line.materialCost} onChange={(v) => updateLine(index, "materialCost", v)} /></td><td className="p-2"><Cell type="number" value={line.laborCost} onChange={(v) => updateLine(index, "laborCost", v)} /></td><td className="p-2"><Cell type="number" value={line.equipmentCost} onChange={(v) => updateLine(index, "equipmentCost", v)} /></td><td className="p-2"><Cell type="number" value={line.otherCost} onChange={(v) => updateLine(index, "otherCost", v)} /></td><td className="p-2"><Cell type="number" value={line.unitRate} onChange={(v) => updateLine(index, "unitRate", v)} placeholder={rate.toFixed(2)} /></td><td className="p-2 min-w-[190px]"><select className="h-9 w-full rounded-md border border-slate-200 bg-white px-2 text-xs" value={line.costItemId} onChange={(e) => updateLine(index, "costItemId", e.target.value)}><option value="">بدون ربط</option>{(costItems.data ?? []).map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></td><td className="p-3 whitespace-nowrap font-bold text-[#18324b]">{money.format((Number(line.quantity) || 0) * rate)}</td><td className="p-2"><Button type="button" variant="ghost" size="icon" className="text-rose-600" disabled={lines.length === 1} onClick={() => setLines(lines.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></Button></td></tr>; })}</tbody></table></div>
      <div className="flex flex-wrap items-center justify-between gap-3"><Button type="button" variant="outline" className="gap-2" onClick={() => setLines([...lines, blankLine()])}><Plus className="h-4 w-4" /> إضافة بند</Button><div className="rounded-xl bg-[#f5f0e5] px-5 py-3 text-sm text-[#18324b]">إجمالي التكلفة التقديرية: <strong className="text-xl">{money.format(totals)} ر.س</strong></div></div>
      <textarea className="min-h-20 w-full rounded-md border border-slate-200 bg-white p-3 text-sm" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="ملاحظات وشروط التسعير والافتراضات" /><Button className="w-full gap-2 bg-[#18324b] hover:bg-[#244767]" disabled={create.isPending || update.isPending}><Save className="h-4 w-4" /> {create.isPending || update.isPending ? "جارٍ الحفظ..." : editingId ? "حفظ تعديل المقايسة" : "حفظ المقايسة"}</Button>{editingId && <Button type="button" variant="outline" className="w-full" onClick={() => { setEditingId(null); setLines([blankLine()]); }}>إلغاء التعديل والبدء بمقايسة جديدة</Button>}{create.isError && <p className="text-sm text-rose-700">تعذر حفظ المقايسة: {create.error.message}</p>}{create.isSuccess && <p className="text-sm text-emerald-700">تم حفظ المقايسة بنجاح.</p>}
    </form></CardContent></Card>
    <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-[#18324b]"><ClipboardList className="h-5 w-5 text-[#b28a3b]" /> سجل المقايسات</CardTitle><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث بالكود أو الاسم أو العميل" className="mt-3" /></CardHeader><CardContent className="space-y-3">{estimates.isLoading ? <p className="py-8 text-center text-sm text-slate-500">جارٍ التحميل...</p> : estimates.data?.length ? estimates.data.map((estimate) => <div key={estimate.id} className="rounded-xl border border-slate-100 bg-white p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold text-[#18324b]">{estimate.name}</p><p className="mt-1 text-xs text-slate-500">{estimate.code} · إصدار {estimate.version}</p></div><Badge variant="outline">{estimate.status === "draft" ? "مسودة" : estimate.status === "submitted" ? "للمراجعة" : estimate.status === "approved" ? "معتمدة" : "مؤرشفة"}</Badge></div><p className="mt-2 text-xs text-slate-500">{estimate.projectId ? `مرتبطة بالمشروع رقم ${estimate.projectId}` : "مقايسة مستقلة"}</p><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={() => setEditingId(estimate.id)}>تعديل</Button><EstimatePreview id={estimate.id} /><Button type="button" variant="outline" size="sm" className="gap-1 text-rose-700" disabled={deleteEstimate.isPending} onClick={() => window.confirm(`حذف المقايسة «${estimate.name}»؟ لا يمكن التراجع عن الحذف.`) && deleteEstimate.mutate({ id: estimate.id })}><Trash2 className="h-3.5 w-3.5" /> حذف</Button></div></div>) : <div className="rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">لا توجد مقايسات محفوظة بعد. يمكنك البدء بمقايسة مستقلة أو ربطها بمشروع.</div>}</CardContent></Card></section>
  </div></div>;
}
function EstimatePreview({ id }: { id: number }) { const [open, setOpen] = useState(false); const { data, isLoading } = trpc.erp.estimates.get.useQuery({ id }, { enabled: open }); return <><Button type="button" variant="outline" size="sm" className="gap-1 text-[#18324b]" onClick={() => setOpen(!open)}><Eye className="h-3.5 w-3.5" /> {open ? "إخفاء المعاينة" : "معاينة"}</Button>{open && <div className="mt-3 w-full rounded-xl border border-[#b28a3b]/30 bg-[#fffaf0] p-3 text-xs leading-6">{isLoading ? "جارٍ تحميل المعاينة..." : data ? <><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="text-sm text-[#18324b]">{data.estimate.name}</strong><p>{data.estimate.code} · إصدار {data.estimate.version}</p></div><Button type="button" size="sm" variant="outline" onClick={() => window.print()}>تنزيل PDF / طباعة</Button></div><p className="mt-2">{data.estimate.clientName || "بدون عميل محدد"} · {data.estimate.siteLocation || "بدون موقع محدد"}</p><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[520px] text-right"><thead><tr className="border-b border-amber-200"><th className="p-1">الوصف</th><th className="p-1">الوحدة</th><th className="p-1">الكمية</th><th className="p-1">سعر الوحدة</th><th className="p-1">الإجمالي</th></tr></thead><tbody>{data.lines.map((line) => <tr key={line.id} className="border-b border-amber-100"><td className="p-1">{line.description}</td><td className="p-1">{line.unit}</td><td className="p-1">{line.quantity}</td><td className="p-1">{line.unitRate}</td><td className="p-1 font-semibold">{line.totalCost}</td></tr>)}</tbody></table></div></> : "تعذر تحميل المعاينة."}</div>}</>; }
function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <div><Label className="text-xs text-slate-600">{label}</Label><Input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="mt-1 bg-white" /></div>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <div><Label className="text-xs text-slate-600">{label}</Label><select className="mt-1 h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm" value={value} onChange={(e) => onChange(e.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>; }
function Cell({ value, onChange, type = "text", placeholder }: { value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-9 w-full min-w-[78px] rounded-md border border-slate-200 bg-white px-2 text-xs" />; }
