import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ClipboardCheck, FileArchive, HardHat, UsersRound, WalletCards } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

const money = new Intl.NumberFormat("ar-SA", { maximumFractionDigits: 2 });
const tabs = [
  { key: "cost", label: "مركز التكلفة", icon: WalletCards },
  { key: "vendors", label: "الموردون والمقاولون", icon: HardHat },
  { key: "certificates", label: "المستخلصات", icon: FileArchive },
  { key: "custody", label: "العهد", icon: WalletCards },
  { key: "attendance", label: "الحضور", icon: UsersRound },
  { key: "attachments", label: "المرفقات", icon: FileArchive },
] as const;

type TabKey = (typeof tabs)[number]["key"];

export default function Operations() {
  const [, setLocation] = useLocation();
  const [tab, setTab] = useState<TabKey>("cost");
  const { data: projects = [] } = trpc.erp.projects.list.useQuery();
  const { data: stages = [] } = trpc.erp.stages.list.useQuery();
  const selectedProjectId = projects[0]?.id;
  const cost = trpc.erp.reports.costCenter.useQuery({ projectId: selectedProjectId ?? 0 }, { enabled: Boolean(selectedProjectId) });
  const vendors = trpc.erp.vendors.list.useQuery();
  const certificates = trpc.erp.certificates.list.useQuery();
  const custody = trpc.erp.custody.list.useQuery();
  const attendance = trpc.erp.attendance.list.useQuery();
  const attachments = trpc.erp.attachments.list.useQuery({ projectId: selectedProjectId ?? 0 }, { enabled: Boolean(selectedProjectId) });
  const utils = trpc.useUtils();
  const createVendor = trpc.erp.vendors.create.useMutation({ onSuccess: () => utils.erp.vendors.list.invalidate() });
  const createCertificate = trpc.erp.certificates.create.useMutation({ onSuccess: () => { utils.erp.certificates.list.invalidate(); utils.erp.reports.costCenter.invalidate(); } });
  const createCustody = trpc.erp.custody.create.useMutation({ onSuccess: () => { utils.erp.custody.list.invalidate(); utils.erp.reports.costCenter.invalidate(); } });
  const createAttendance = trpc.erp.attendance.create.useMutation({ onSuccess: () => utils.erp.attendance.list.invalidate() });
  const createAttachment = trpc.erp.attachments.create.useMutation({ onSuccess: () => attachments.refetch() });
  const [vendor, setVendor] = useState({ name: "", taxNumber: "", commercialRegistration: "", iban: "", contact: "" });
  const [certificate, setCertificate] = useState({ projectId: "", stageId: "", vendorId: "", certificateNumber: "", description: "", preTaxAmount: "", taxRate: "15", paidAmount: "", certificateDate: "" });
  const [custodyForm, setCustodyForm] = useState({ projectId: "", stageId: "", holderName: "", issueDate: "", issuedAmount: "", settledAmount: "" });
  const [attendanceForm, setAttendanceForm] = useState({ projectId: "", stageId: "", employeeCode: "", employeeName: "", attendanceDate: "", checkIn: "", checkOut: "", status: "present" as "present" | "absent" | "late" | "leave", notes: "" });
  const [attachment, setAttachment] = useState({ projectId: "", entityType: "certificate", entityId: "", documentType: "", fileName: "", fileUrl: "" });

  const projectOptions = projects.map((p) => ({ value: String(p.id), label: p.name }));
  const stageOptions = stages.filter((s) => !selectedProjectId || s.projectId === selectedProjectId).map((s) => ({ value: String(s.id), label: s.name }));

  return <DashboardLayout><div dir="rtl" className="min-h-screen bg-[#f7f8fa] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl space-y-6">
    <header><Button variant="ghost" className="mb-2 gap-2 px-0 text-slate-500" onClick={() => setLocation("/")}><ArrowRight className="h-4 w-4" /> العودة للوحة التنفيذ</Button><h1 className="text-3xl font-bold text-[#18324b]">الوحدات التشغيلية</h1><p className="mt-2 text-sm text-slate-500">سجل العملية مرة واحدة، ثم تابع أثرها في التقارير ومركز التكلفة دون إعادة إدخال.</p></header>
    <div className="flex flex-wrap gap-2 rounded-2xl bg-white p-2 shadow-sm">{tabs.map(({ key, label, icon: Icon }) => <Button key={key} variant={tab === key ? "default" : "ghost"} className={tab === key ? "bg-[#18324b]" : ""} onClick={() => setTab(key)}><Icon className="ml-2 h-4 w-4" />{label}</Button>)}</div>
    {tab === "cost" && <CostCenterPanel data={cost.data ?? []} loading={cost.isLoading} projectName={projects.find((p) => p.id === selectedProjectId)?.name ?? ""} />}
    {tab === "vendors" && <div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><FormCard title="إضافة مورد أو مقاول"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); if (!vendor.name) return; createVendor.mutate(vendor); setVendor({ name: "", taxNumber: "", commercialRegistration: "", iban: "", contact: "" }); }}><Field label="الاسم" value={vendor.name} onChange={(v) => setVendor({ ...vendor, name: v })} /><Field label="الرقم الضريبي" value={vendor.taxNumber} onChange={(v) => setVendor({ ...vendor, taxNumber: v })} /><Field label="السجل التجاري" value={vendor.commercialRegistration} onChange={(v) => setVendor({ ...vendor, commercialRegistration: v })} /><Field label="IBAN" value={vendor.iban} onChange={(v) => setVendor({ ...vendor, iban: v })} /><Field label="بيانات الاتصال" value={vendor.contact} onChange={(v) => setVendor({ ...vendor, contact: v })} /><Button className="w-full bg-[#18324b]" disabled={createVendor.isPending}>حفظ المورد</Button></form></FormCard><ListCard title="سجل الموردين والمقاولين">{(vendors.data ?? []).map((item) => <ListRow key={item.id} title={item.name} subtitle={[item.taxNumber, item.iban].filter(Boolean).join(" · ") || "بيانات الامتثال غير مكتملة"} badge="مرجع مركزي" />)}</ListCard></div>}
    {tab === "certificates" && <div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><FormCard title="إضافة مستخلص مقاول"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); if (!certificate.projectId || !certificate.certificateNumber || !certificate.preTaxAmount) return; createCertificate.mutate({ ...certificate, projectId: Number(certificate.projectId), stageId: certificate.stageId ? Number(certificate.stageId) : undefined, vendorId: certificate.vendorId ? Number(certificate.vendorId) : undefined, preTaxAmount: Number(certificate.preTaxAmount), taxRate: Number(certificate.taxRate), paidAmount: Number(certificate.paidAmount || 0) }); }}><SelectField label="المشروع" value={certificate.projectId} options={projectOptions} onChange={(v) => setCertificate({ ...certificate, projectId: v })} /><SelectField label="المرحلة" value={certificate.stageId} options={stageOptions} onChange={(v) => setCertificate({ ...certificate, stageId: v })} /><SelectField label="المقاول" value={certificate.vendorId} options={(vendors.data ?? []).map((v) => ({ value: String(v.id), label: v.name }))} onChange={(v) => setCertificate({ ...certificate, vendorId: v })} /><Field label="رقم المستخلص" value={certificate.certificateNumber} onChange={(v) => setCertificate({ ...certificate, certificateNumber: v })} /><Field label="الوصف" value={certificate.description} onChange={(v) => setCertificate({ ...certificate, description: v })} /><div className="grid grid-cols-2 gap-3"><Field label="قبل الضريبة" type="number" value={certificate.preTaxAmount} onChange={(v) => setCertificate({ ...certificate, preTaxAmount: v })} /><Field label="المدفوع" type="number" value={certificate.paidAmount} onChange={(v) => setCertificate({ ...certificate, paidAmount: v })} /></div><Field label="تاريخ المستخلص" type="date" value={certificate.certificateDate} onChange={(v) => setCertificate({ ...certificate, certificateDate: v })} /><Button className="w-full bg-[#18324b]" disabled={createCertificate.isPending}>إرسال للمراجعة</Button></form></FormCard><ListCard title="آخر المستخلصات">{(certificates.data ?? []).map((item) => <ListRow key={item.id} title={item.certificateNumber} subtitle={`${money.format(Number(item.totalAmount))} ر.س · مدفوع ${money.format(Number(item.paidAmount))}`} badge={item.status} />)}</ListCard></div>}
    {tab === "custody" && <div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><FormCard title="تسجيل عهدة"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); if (!custodyForm.projectId || !custodyForm.holderName || !custodyForm.issuedAmount) return; createCustody.mutate({ ...custodyForm, projectId: Number(custodyForm.projectId), stageId: custodyForm.stageId ? Number(custodyForm.stageId) : undefined, issuedAmount: Number(custodyForm.issuedAmount), settledAmount: Number(custodyForm.settledAmount || 0) }); }}><SelectField label="المشروع" value={custodyForm.projectId} options={projectOptions} onChange={(v) => setCustodyForm({ ...custodyForm, projectId: v })} /><SelectField label="المرحلة" value={custodyForm.stageId} options={stageOptions} onChange={(v) => setCustodyForm({ ...custodyForm, stageId: v })} /><Field label="الموظف المسؤول" value={custodyForm.holderName} onChange={(v) => setCustodyForm({ ...custodyForm, holderName: v })} /><div className="grid grid-cols-2 gap-3"><Field label="قيمة العهدة" type="number" value={custodyForm.issuedAmount} onChange={(v) => setCustodyForm({ ...custodyForm, issuedAmount: v })} /><Field label="المسدد" type="number" value={custodyForm.settledAmount} onChange={(v) => setCustodyForm({ ...custodyForm, settledAmount: v })} /></div><Field label="تاريخ الصرف" type="date" value={custodyForm.issueDate} onChange={(v) => setCustodyForm({ ...custodyForm, issueDate: v })} /><Button className="w-full bg-[#18324b]" disabled={createCustody.isPending}>حفظ العهدة</Button></form></FormCard><ListCard title="سجل العهد">{(custody.data ?? []).map((item) => <ListRow key={item.id} title={item.holderName} subtitle={`${money.format(Number(item.issuedAmount))} ر.س · الرصيد ${money.format(Number(item.issuedAmount) - Number(item.settledAmount))}`} badge={item.status} />)}</ListCard></div>}
    {tab === "attendance" && <div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><FormCard title="تسجيل حضور"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); if (!attendanceForm.projectId || !attendanceForm.employeeName || !attendanceForm.attendanceDate) return; createAttendance.mutate({ ...attendanceForm, projectId: Number(attendanceForm.projectId), stageId: attendanceForm.stageId ? Number(attendanceForm.stageId) : undefined }); }}><SelectField label="المشروع" value={attendanceForm.projectId} options={projectOptions} onChange={(v) => setAttendanceForm({ ...attendanceForm, projectId: v })} /><SelectField label="المرحلة" value={attendanceForm.stageId} options={stageOptions} onChange={(v) => setAttendanceForm({ ...attendanceForm, stageId: v })} /><div className="grid grid-cols-2 gap-3"><Field label="كود الموظف" value={attendanceForm.employeeCode} onChange={(v) => setAttendanceForm({ ...attendanceForm, employeeCode: v })} /><Field label="اسم الموظف" value={attendanceForm.employeeName} onChange={(v) => setAttendanceForm({ ...attendanceForm, employeeName: v })} /></div><Field label="التاريخ" type="date" value={attendanceForm.attendanceDate} onChange={(v) => setAttendanceForm({ ...attendanceForm, attendanceDate: v })} /><div className="grid grid-cols-2 gap-3"><Field label="دخول" type="time" value={attendanceForm.checkIn} onChange={(v) => setAttendanceForm({ ...attendanceForm, checkIn: v })} /><Field label="خروج" type="time" value={attendanceForm.checkOut} onChange={(v) => setAttendanceForm({ ...attendanceForm, checkOut: v })} /></div><SelectField label="الحالة" value={attendanceForm.status} options={[{ value: "present", label: "حاضر" }, { value: "late", label: "متأخر" }, { value: "absent", label: "غائب" }, { value: "leave", label: "إجازة" }]} onChange={(v) => setAttendanceForm({ ...attendanceForm, status: v as typeof attendanceForm.status })} /><Button className="w-full bg-[#18324b]" disabled={createAttendance.isPending}>حفظ الحضور</Button></form></FormCard><ListCard title="سجل الحضور">{(attendance.data ?? []).map((item) => <ListRow key={item.id} title={item.employeeName} subtitle={`${String(item.attendanceDate).slice(0, 10)} · ${item.checkIn || "—"} - ${item.checkOut || "—"}`} badge={item.status} />)}</ListCard></div>}
    {tab === "attachments" && <div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><FormCard title="إضافة مستند مرتبط"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); if (!attachment.projectId || !attachment.entityId || !attachment.documentType || !attachment.fileName || !attachment.fileUrl) return; createAttachment.mutate({ ...attachment, projectId: Number(attachment.projectId), entityId: Number(attachment.entityId) }); }}><SelectField label="المشروع" value={attachment.projectId} options={projectOptions} onChange={(v) => setAttachment({ ...attachment, projectId: v })} /><SelectField label="نوع الكيان" value={attachment.entityType} options={[{ value: "certificate", label: "مستخلص" }, { value: "vendor", label: "مقاول" }, { value: "expense", label: "مصروف" }, { value: "project", label: "مشروع" }]} onChange={(v) => setAttachment({ ...attachment, entityType: v })} /><Field label="رقم الكيان" type="number" value={attachment.entityId} onChange={(v) => setAttachment({ ...attachment, entityId: v })} /><Field label="نوع المستند" value={attachment.documentType} onChange={(v) => setAttachment({ ...attachment, documentType: v })} /><Field label="اسم الملف" value={attachment.fileName} onChange={(v) => setAttachment({ ...attachment, fileName: v })} /><Field label="رابط الملف" value={attachment.fileUrl} onChange={(v) => setAttachment({ ...attachment, fileUrl: v })} /><Button className="w-full bg-[#18324b]" disabled={createAttachment.isPending}>حفظ رابط المستند</Button></form></FormCard><ListCard title="مرفقات المشروع">{(attachments.data ?? []).map((item) => <ListRow key={item.id} title={item.fileName} subtitle={`${item.documentType} · ${item.entityType} #${item.entityId}`} badge="فتح المستند" />)}</ListCard></div>}
  </div></div></DashboardLayout>;
}

function CostCenterPanel({ data, loading, projectName }: { data: any[]; loading: boolean; projectName: string }) { return <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center justify-between text-lg text-[#18324b]"><span>مركز التكلفة — {projectName}</span><Badge variant="outline">خامات · تشغيل · إدارة</Badge></CardTitle></CardHeader><CardContent>{loading ? <div className="py-10 text-center text-slate-500">جارٍ التحميل...</div> : <div className="space-y-4">{data.map((item) => <div key={item.stage.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center justify-between"><div><p className="font-bold text-[#18324b]">{item.stage.name}</p><p className="text-xs text-slate-500">ميزانية مخططة {money.format(Number(item.stage.plannedBudget))} ر.س · تقدم {Number(item.stage.actualProgress)}%</p></div><Badge>{item.stage.status}</Badge></div><div className="mt-3 grid gap-2 sm:grid-cols-3">{Object.entries(item.byType as Record<string, { total: number; paid: number; outstanding: number }>).map(([type, values]) => <div key={type} className="rounded-xl bg-white p-3"><p className="text-xs text-slate-500">{typeLabel(type)}</p><p className="mt-1 font-bold text-[#18324b]">{money.format(values.total)} ر.س</p><p className="text-xs text-slate-500">مدفوع {money.format(values.paid)} · مستحق {money.format(values.outstanding)}</p></div>)}</div><div className="mt-4 overflow-x-auto rounded-xl border border-slate-100 bg-white"><table className="w-full min-w-[680px] text-right text-xs"><thead><tr className="border-b border-slate-100 text-slate-500"><th className="px-3 py-2">البند / الوصف</th><th className="px-3 py-2">نوع التكلفة</th><th className="px-3 py-2">قبل الضريبة</th><th className="px-3 py-2">بعد الضريبة</th><th className="px-3 py-2">المدفوع</th><th className="px-3 py-2">المستحق</th></tr></thead><tbody>{item.expenses.map((expense: any) => <tr key={expense.id} className="border-b border-slate-50"><td className="px-3 py-2 font-semibold text-[#18324b]">{expense.description}</td><td className="px-3 py-2">{typeLabel(expense.expenseType)}</td><td className="px-3 py-2">{money.format(Number(expense.preTaxAmount))}</td><td className="px-3 py-2">{money.format(Number(expense.totalAmount))}</td><td className="px-3 py-2">{money.format(Number(expense.paidAmount))}</td><td className="px-3 py-2">{money.format(Math.max(Number(expense.totalAmount) - Number(expense.paidAmount), 0))}</td></tr>)}</tbody></table></div></div>) || <p className="py-10 text-center text-slate-500">لا توجد مراحل مسجلة بعد.</p>}</div>}</CardContent></Card>; }
function typeLabel(type: string) { return ({ materials: "تكلفة خامات", operating_tools: "عدد تشغيل", equipment_rental: "إيجار معدات", contractor: "مقاولات", transport: "نقل", maintenance: "صيانة", services: "خدمات", operating: "تشغيل", administrative: "إدارة" } as Record<string, string>)[type] || type; }
function FormCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg text-[#18324b]">{title}</CardTitle></CardHeader><CardContent>{children}</CardContent></Card>; }
function ListCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg text-[#18324b]">{title}</CardTitle></CardHeader><CardContent className="max-h-[620px] space-y-3 overflow-auto">{children || <p className="py-10 text-center text-slate-500">لا توجد بيانات بعد.</p>}</CardContent></Card>; }
function ListRow({ title, subtitle, badge }: { title: string; subtitle: string; badge: string }) { return <div className="flex items-center justify-between rounded-xl border border-slate-100 bg-white p-3"><div><p className="font-semibold text-[#18324b]">{title}</p><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><Badge variant="outline">{badge}</Badge></div>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (v: string) => void; type?: string }) { return <div className="space-y-1.5"><Label className="text-sm text-slate-600">{label}</Label><Input dir="rtl" type={type} value={value} onChange={(e) => onChange(e.target.value)} className="h-10 border-slate-200 bg-white" /></div>; }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (v: string) => void }) { return <div className="space-y-1.5"><Label className="text-sm text-slate-600">{label}</Label><select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm text-slate-700" required><option value="">اختر...</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>; }
