import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BarChart3, CircleDollarSign, FileCheck2, WalletCards } from "lucide-react";
import { useLocation } from "wouter";

const money = new Intl.NumberFormat("ar-SA", { maximumFractionDigits: 2 });
const labels: Record<string, { label: string; color: string }> = { on_track: { label: "على المسار", color: "bg-emerald-50 text-emerald-700" }, warning: { label: "يحتاج متابعة", color: "bg-amber-50 text-amber-700" }, critical: { label: "حرج", color: "bg-rose-50 text-rose-700" } };

export default function Reports() {
  const [, setLocation] = useLocation();
  const { data: summaries = [], isLoading } = trpc.erp.dashboard.summary.useQuery();
  const total = summaries.reduce((acc, item) => ({ planned: acc.planned + item.plannedBudget, actual: acc.actual + item.actualCost, paid: acc.paid + item.paidCost, collections: acc.collections + item.collectionsReceived, cashGap: acc.cashGap + item.cashGap, approvals: acc.approvals + item.pendingApprovals }), { planned: 0, actual: 0, paid: 0, collections: 0, cashGap: 0, approvals: 0 });
  return <DashboardLayout><div dir="rtl" className="min-h-screen bg-[#f7f8fa] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl space-y-6"><header><Button variant="ghost" className="mb-2 gap-2 px-0 text-slate-500" onClick={() => setLocation("/")}><ArrowRight className="h-4 w-4" /> العودة للوحة التنفيذ</Button><h1 className="text-3xl font-bold text-[#18324b]">التقارير الإدارية</h1><p className="mt-2 text-sm text-slate-500">مقارنة موحدة بين المخطط والفعلي والسيولة والموافقات عبر المشاريع.</p></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BarChart3} label="الميزانية المخططة" value={`${money.format(total.planned)} ر.س`} /><Metric icon={CircleDollarSign} label="التكلفة الفعلية" value={`${money.format(total.actual)} ر.س`} /><Metric icon={WalletCards} label="التحصيلات" value={`${money.format(total.collections)} ر.س`} /><Metric icon={FileCheck2} label="الموافقات المعلقة" value={String(total.approvals)} /></section><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg text-[#18324b]">مقارنة المشاريع</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[820px] text-right text-sm"><thead><tr className="border-b border-slate-100 text-xs text-slate-500"><th className="px-3 py-3">المشروع</th><th className="px-3 py-3">الحالة</th><th className="px-3 py-3">الإنجاز</th><th className="px-3 py-3">استخدام الميزانية</th><th className="px-3 py-3">المدفوع</th><th className="px-3 py-3">التحصيل</th><th className="px-3 py-3">الفجوة</th><th className="px-3 py-3">الموافقات</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={8} className="py-12 text-center text-slate-500">جارٍ التحميل...</td></tr> : summaries.map((item) => { const status = labels[item.status] ?? labels.warning; return <tr key={item.project.id} className="cursor-pointer border-b border-slate-50 hover:bg-slate-50" onClick={() => setLocation(`/projects/${item.project.id}`)}><td className="px-3 py-4 font-semibold text-[#18324b]">{item.project.name}</td><td className="px-3 py-4"><Badge className={status.color}>{status.label}</Badge></td><td className="px-3 py-4">{item.progress}%</td><td className="px-3 py-4">{item.budgetUsage}%</td><td className="px-3 py-4">{money.format(item.paidCost)}</td><td className="px-3 py-4">{money.format(item.collectionsReceived)}</td><td className="px-3 py-4">{money.format(item.cashGap)}</td><td className="px-3 py-4">{item.pendingApprovals}{item.overdueApprovals ? ` (${item.overdueApprovals} متأخرة)` : ""}</td></tr>; })}</tbody></table></CardContent></Card></div></div></DashboardLayout>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof BarChart3; label: string; value: string }) { return <Card className="border-0 shadow-sm"><CardContent className="p-5"><Icon className="h-5 w-5 text-[#b28a3b]" /><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-[#18324b]">{value}</p></CardContent></Card>; }
