import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Download, FileBarChart2, Printer } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import * as XLSX from "xlsx";

const money = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });
type ReportKind = "supplier" | "cost" | "income";

function exportRows(rows: Array<Record<string, unknown>>, fileName: string) {
  const worksheet = XLSX.utils.json_to_sheet(rows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "التقرير");
  XLSX.writeFile(workbook, `${fileName}.xlsx`);
}

export default function StandaloneFinancialReport() {
  const [location, setLocation] = useLocation();
  const kind: ReportKind = location.startsWith("/supplier-statements") ? "supplier" : location.startsWith("/cost-center") ? "cost" : "income";
  const titles = { supplier: "كشوف حسابات الموردين", cost: "مركز التكلفة", income: "قائمة الدخل" };
  const descriptions = { supplier: "كشف تفصيلي لحركات المورد والمقاول مع المدفوع والمستحق والرصيد التراكمي.", cost: "تفصيل أداء وتكلفة مراحل المشروع وبنود التكلفة من الحركات الفعلية.", income: "قائمة دخل تفصيلية حسب المشروع والفترة من الإيرادات والمصروفات والرواتب." };
  const { data: projects = [] } = trpc.erp.projects.list.useQuery();
  const { data: vendors = [] } = trpc.erp.vendors.list.useQuery();
  const [projectId, setProjectId] = useState("");
  const [vendorId, setVendorId] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const selectedProjectId = Number(projectId || projects[0]?.id || 0);
  const selectedVendorId = Number(vendorId || vendors[0]?.id || 0);
  const supplier = trpc.erp.reports.supplierStatement.useQuery({ projectId: selectedProjectId, vendorId: selectedVendorId }, { enabled: kind === "supplier" && Boolean(selectedProjectId && selectedVendorId) });
  const costCenter = trpc.erp.reports.projectStageDetail.useQuery({ projectId: selectedProjectId }, { enabled: kind === "cost" && Boolean(selectedProjectId) });
  const income = trpc.erp.reports.financialSummary.useQuery({ projectId: selectedProjectId, from: from || undefined, to: to || undefined }, { enabled: kind === "income" && Boolean(selectedProjectId) });

  const supplierMovements = useMemo(() => {
    const rows = [
      ...(supplier.data?.expenses ?? []).map((row) => ({ date: row.expenseDate, reference: row.reference || `مصروف #${row.id}`, description: row.description, type: "مصروف", total: Number(row.totalAmount || 0), paid: Number(row.paidAmount || 0) })),
      ...(supplier.data?.certificates ?? []).map((row) => ({ date: row.certificateDate, reference: row.certificateNumber, description: row.description || "مستخلص مقاول", type: "مستخلص", total: Number(row.totalAmount || 0), paid: Number(row.paidAmount || 0) })),
    ].filter((row) => (!from || !row.date || String(row.date).slice(0, 10) >= from) && (!to || !row.date || String(row.date).slice(0, 10) <= to)).sort((a, b) => String(a.date || "").localeCompare(String(b.date || "")));
    let balance = 0;
    return rows.map((row) => { const outstanding = Math.max(row.total - row.paid, 0); balance += outstanding; return { ...row, outstanding, balance }; });
  }, [supplier.data, from, to]);

  const incomeRows = [{ البند: "الإيرادات المعترف بها", القيمة: income.data?.revenue ?? 0 }, { البند: "المصروفات قبل الضريبة", القيمة: income.data?.expensesPreTax ?? 0 }, { البند: "ضريبة المصروفات", القيمة: income.data?.expensesTax ?? 0 }, { البند: "إجمالي المصروفات", القيمة: income.data?.expensesTotal ?? 0 }, { البند: "إجمالي الرواتب", القيمة: income.data?.payrollTotal ?? 0 }, { البند: "صافي الدخل", القيمة: Number(income.data?.revenue ?? 0) - Number(income.data?.expensesTotal ?? 0) - Number(income.data?.payrollTotal ?? 0) }];
  const reportRows: Array<Record<string, unknown>> = kind === "supplier" ? supplierMovements.map((row) => ({ التاريخ: row.date ? String(row.date).slice(0, 10) : "—", النوع: row.type, المرجع: row.reference, البيان: row.description, الإجمالي: row.total, المدفوع: row.paid, المستحق: row.outstanding, "الرصيد التراكمي": row.balance })) : kind === "cost" ? (costCenter.data?.rows ?? []).map((row) => ({ النوع: row.rowType === "stage" ? "مرحلة" : "بند تكلفة", الكود: row.code, البيان: row.name, المرحلة: row.stageName, الميزانية: row.plannedBudget, الفعلي: row.actual, المدفوع: row.paidAmount, المستحق: row.outstanding, الانحراف: row.variance, "الاستهلاك %": row.consumptionPct })) : incomeRows;

  return <DashboardLayout><div dir="rtl" className="report-shell min-h-screen bg-[#f7f8fa] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl space-y-6"><header className="report-header"><Button variant="ghost" className="mb-2 gap-2 px-0 text-slate-500 print:hidden" onClick={() => setLocation("/reports")}><ArrowRight className="h-4 w-4" /> العودة إلى التقارير</Button><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#b28a3b]">تقرير مالي مستقل</p><h1 className="text-3xl font-bold text-[#18324b]">{titles[kind]}</h1><p className="mt-2 text-sm text-slate-500">{descriptions[kind]}</p></div><div className="flex gap-2 print:hidden"><Button variant="outline" onClick={() => exportRows(reportRows, titles[kind])} disabled={!reportRows.length}><Download className="ml-2 h-4 w-4" />تصدير Excel</Button><Button variant="outline" onClick={() => window.print()}><Printer className="ml-2 h-4 w-4" />طباعة</Button></div></div></header>
    <Card className="border-0 shadow-sm"><CardContent className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4"><Filter label="المشروع" value={projectId || String(projects[0]?.id || "")} options={projects.map((item) => ({ value: String(item.id), label: item.name }))} onChange={setProjectId} /><>{kind === "supplier" && <Filter label="المورد أو المقاول" value={vendorId || String(vendors[0]?.id || "")} options={vendors.map((item) => ({ value: String(item.id), label: item.name }))} onChange={setVendorId} />}</>{<DateField label="من تاريخ" value={from} onChange={setFrom} />}{<DateField label="إلى تاريخ" value={to} onChange={setTo} />}</CardContent></Card>
    {kind === "supplier" && <><section className="grid gap-4 sm:grid-cols-3"><Metric label="إجمالي الحركة" value={`${money.format(supplier.data?.debit ?? 0)} ر.س`} /><Metric label="المدفوع" value={`${money.format(supplier.data?.credit ?? 0)} ر.س`} /><Metric label="الرصيد المستحق" value={`${money.format(supplier.data?.balance ?? 0)} ر.س`} /></section><MovementTable rows={supplierMovements} /></>}
    {kind === "cost" && <><section className="grid gap-4 sm:grid-cols-4"><Metric label="الميزانية" value={`${money.format(costCenter.data?.total.plannedBudget ?? 0)} ر.س`} /><Metric label="التكلفة الفعلية" value={`${money.format(costCenter.data?.total.actual ?? 0)} ر.س`} /><Metric label="المدفوع" value={`${money.format(costCenter.data?.total.paidAmount ?? 0)} ر.س`} /><Metric label="المستحق" value={`${money.format(costCenter.data?.total.outstanding ?? 0)} ر.س`} /></section><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-[#18324b]"><FileBarChart2 className="h-5 w-5 text-[#b28a3b]" />تفصيل المراحل وبنود التكلفة</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-right text-sm"><thead><tr className="bg-[#18324b] text-white"><th className="p-3">النوع</th><th className="p-3">الكود</th><th className="p-3">البيان</th><th className="p-3">المرحلة</th><th className="p-3">الميزانية</th><th className="p-3">الفعلي</th><th className="p-3">المدفوع</th><th className="p-3">المستحق</th><th className="p-3">الانحراف</th></tr></thead><tbody>{(costCenter.data?.rows ?? []).map((row) => <tr key={`${row.rowType}-${row.id}`} className="border-b border-slate-100"><td className="p-3">{row.rowType === "stage" ? "مرحلة" : "بند تكلفة"}</td><td className="p-3 font-semibold">{row.code}</td><td className="p-3">{row.name}</td><td className="p-3">{row.stageName}</td><td className="p-3">{money.format(row.plannedBudget)}</td><td className="p-3">{money.format(row.actual)}</td><td className="p-3 text-emerald-700">{money.format(row.paidAmount)}</td><td className="p-3 text-amber-700">{money.format(row.outstanding)}</td><td className={`p-3 ${row.variance < 0 ? "text-rose-700" : "text-emerald-700"}`}>{money.format(row.variance)}</td></tr>)}</tbody></table></div></CardContent></Card></>}
    {kind === "income" && <><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Metric label="الإيرادات المعترف بها" value={`${money.format(income.data?.revenue ?? 0)} ر.س`} /><Metric label="إجمالي المصروفات والرواتب" value={`${money.format(Number(income.data?.expensesTotal ?? 0) + Number(income.data?.payrollTotal ?? 0))} ر.س`} /><Metric label="صافي الدخل" value={`${money.format(Number(income.data?.revenue ?? 0) - Number(income.data?.expensesTotal ?? 0) - Number(income.data?.payrollTotal ?? 0))} ر.س`} /></section><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-[#18324b]">تفصيل قائمة الدخل</CardTitle></CardHeader><CardContent><table className="w-full text-right text-sm"><thead><tr className="bg-[#18324b] text-white"><th className="p-3">البند</th><th className="p-3">القيمة</th></tr></thead><tbody>{incomeRows.map((row, index) => <tr key={index} className="border-b border-slate-100"><td className="p-3 font-semibold">{row.البند}</td><td className="p-3">{money.format(Number(row.القيمة))} ر.س</td></tr>)}</tbody></table></CardContent></Card></>}
  </div></div></DashboardLayout>;
}

function Filter({ label, value, options, onChange }: { label: string; value: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void }) { return <label className="space-y-1.5 text-sm text-slate-600"><span className="block">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3"><option value="">اختر...</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="space-y-1.5 text-sm text-slate-600"><span className="block">{label}</span><input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3" /></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <Card className="border border-slate-100 shadow-sm"><CardContent className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-bold text-[#18324b]">{value}</p></CardContent></Card>; }
function MovementTable({ rows }: { rows: Array<{ date: Date | string | null; reference: string; description: string; type: string; total: number; paid: number; outstanding: number; balance: number }> }) { return <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-[#18324b]">الحركات التفصيلية</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-right text-sm"><thead><tr className="bg-[#18324b] text-white"><th className="p-3">التاريخ</th><th className="p-3">النوع</th><th className="p-3">المرجع</th><th className="p-3">البيان</th><th className="p-3">الإجمالي</th><th className="p-3">المدفوع</th><th className="p-3">المستحق</th><th className="p-3">الرصيد التراكمي</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={`${row.type}-${row.reference}-${row.date}`} className="border-b border-slate-100"><td className="p-3">{row.date ? String(row.date).slice(0, 10) : "—"}</td><td className="p-3"><Badge variant="outline">{row.type}</Badge></td><td className="p-3 font-semibold">{row.reference}</td><td className="p-3">{row.description}</td><td className="p-3">{money.format(row.total)}</td><td className="p-3 text-emerald-700">{money.format(row.paid)}</td><td className="p-3 text-amber-700">{money.format(row.outstanding)}</td><td className="p-3 font-bold text-[#18324b]">{money.format(row.balance)}</td></tr>) : <tr><td colSpan={8} className="p-10 text-center text-slate-500">لا توجد حركات ضمن الفلاتر الحالية.</td></tr>}</tbody></table></div></CardContent></Card>; }
