import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ShieldCheck, UserCog } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";

const roleLabels: Record<string, string> = { manager: "مدير مشروع", finance: "مالي", input: "إدخال", reviewer: "مراجع", viewer: "مشاهدة" };

export default function Users() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const { data: users = [], isLoading } = trpc.erp.users.list.useQuery();
  const { data: projects = [] } = trpc.erp.projects.list.useQuery();
  const { data: members = [] } = trpc.erp.members.list.useQuery();
  const { data: locks = [] } = trpc.erp.controls.locks.useQuery();
  const { data: notifications = [] } = trpc.erp.controls.notifications.useQuery();
  const { data: audit = [] } = trpc.erp.controls.audit.useQuery();
  const assign = trpc.erp.members.assign.useMutation({ onSuccess: () => utils.erp.members.list.invalidate() });
  const lockPeriod = trpc.erp.controls.lockPeriod.useMutation({ onSuccess: () => utils.erp.controls.locks.invalidate() });
  const unlockPeriod = trpc.erp.controls.unlockPeriod.useMutation({ onSuccess: () => utils.erp.controls.locks.invalidate() });
  const markRead = trpc.erp.controls.markNotificationRead.useMutation({ onSuccess: () => utils.erp.controls.notifications.invalidate() });
  const [permissionUserId, setPermissionUserId] = useState("");
  const { data: operationPermissions } = trpc.erp.users.operationPermissions.useQuery({ userId: Number(permissionUserId) }, { enabled: Boolean(permissionUserId) });
  const saveOperationPermissions = trpc.erp.users.saveOperationPermissions.useMutation({ onSuccess: () => utils.erp.users.operationPermissions.invalidate() });
  const [permissionModes, setPermissionModes] = useState<Record<string, "allow" | "approval" | "deny">>({});
  useEffect(() => { if (operationPermissions?.operations) setPermissionModes(Object.fromEntries(operationPermissions.operations.map((item) => [item.key, item.mode]))); }, [operationPermissions]);
  const [form, setForm] = useState({ userId: "", projectId: "", projectRole: "viewer" as "manager" | "finance" | "input" | "reviewer" | "viewer" });
  const [lockForm, setLockForm] = useState({ projectId: "", periodYear: String(new Date().getFullYear()), periodMonth: String(new Date().getMonth() + 1), reason: "" });

  return <DashboardLayout><div dir="rtl" className="min-h-screen bg-[#f7f8fa] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl space-y-6">
    <header><Button variant="ghost" className="mb-2 gap-2 px-0 text-slate-500" onClick={() => setLocation("/")}><ArrowRight className="h-4 w-4" /> العودة للوحة التنفيذ</Button><h1 className="text-3xl font-bold text-[#18324b]">المستخدمون والصلاحيات</h1><p className="mt-2 text-sm text-slate-500">إدارة الوصول حسب المشروع والدور مع الإقفال والتنبيهات وسجل التدقيق.</p></header>
    <section className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]">
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg text-[#18324b]"><UserCog className="h-5 w-5 text-[#b28a3b]" /> إسناد مستخدم لمشروع</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (!form.userId || !form.projectId) return; assign.mutate({ userId: Number(form.userId), projectId: Number(form.projectId), projectRole: form.projectRole }); }}><SelectField label="المستخدم" value={form.userId} options={users.map((u) => ({ value: String(u.id), label: u.name || u.email || `مستخدم #${u.id}` }))} onChange={(v) => setForm({ ...form, userId: v })} /><SelectField label="المشروع" value={form.projectId} options={projects.map((p) => ({ value: String(p.id), label: p.name }))} onChange={(v) => setForm({ ...form, projectId: v })} /><SelectField label="الدور داخل المشروع" value={form.projectRole} options={Object.entries(roleLabels).map(([value, label]) => ({ value, label }))} onChange={(v) => setForm({ ...form, projectRole: v as typeof form.projectRole })} /><div className="rounded-xl bg-slate-50 p-3 text-xs leading-6 text-slate-600">المدير والمالي والإدخال يمكنهم تسجيل الحركات ضمن المشروع. المراجع للمراجعة فقط، والمشاهد للقراءة فقط. الموافقات النهائية متاحة لإدارة النظام.</div><Button className="w-full bg-[#18324b]">حفظ الصلاحية</Button></form></CardContent></Card>
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg text-[#18324b]"><ShieldCheck className="h-5 w-5 text-[#b28a3b]" /> المستخدمون الحاليون</CardTitle><p className="text-xs leading-6 text-slate-500">الحساب الجديد يبدأ افتراضيًا بحالة «يحتاج موافقة المسؤول» في كل العمليات حتى يضبط User 1 مصفوفة صلاحياته.</p></CardHeader><CardContent className="space-y-3">{isLoading ? <div className="py-8 text-center text-sm text-slate-500">جارٍ التحميل...</div> : users.map((user) => <div key={user.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div><p className="font-semibold text-[#18324b]">{user.name || "بدون اسم"}</p><p className="text-xs text-slate-500">{user.email || "بدون بريد"}</p></div><Badge variant="outline">{user.role === "admin" ? "إدارة النظام" : "مستخدم"}</Badge></div>)}</CardContent></Card>
    </section>
    <section className="grid gap-6 lg:grid-cols-2">
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg text-[#18324b]">الإقفال الشهري</CardTitle><p className="text-xs text-slate-500">يقفل الفترة بعد المراجعة ويحتفظ بسبب الإقفال.</p></CardHeader><CardContent><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); if (!lockForm.projectId) return; lockPeriod.mutate({ projectId: Number(lockForm.projectId), periodYear: Number(lockForm.periodYear), periodMonth: Number(lockForm.periodMonth), reason: lockForm.reason }); }}><SelectField label="المشروع" value={lockForm.projectId} options={projects.map((p) => ({ value: String(p.id), label: p.name }))} onChange={(v) => setLockForm({ ...lockForm, projectId: v })} /><div className="grid grid-cols-2 gap-3"><SelectField label="الشهر" value={lockForm.periodMonth} options={Array.from({ length: 12 }, (_, index) => ({ value: String(index + 1), label: String(index + 1) }))} onChange={(v) => setLockForm({ ...lockForm, periodMonth: v })} /><input aria-label="السنة" type="number" value={lockForm.periodYear} onChange={(e) => setLockForm({ ...lockForm, periodYear: e.target.value })} className="h-10 rounded-md border border-slate-200 px-3 text-sm" /></div><input aria-label="سبب الإقفال" value={lockForm.reason} onChange={(e) => setLockForm({ ...lockForm, reason: e.target.value })} placeholder="سبب الإقفال" className="h-10 w-full rounded-md border border-slate-200 px-3 text-sm" /><Button className="w-full bg-[#18324b]">قفل الفترة</Button></form><div className="mt-4 space-y-2">{locks.slice(-5).map((lock) => <div key={lock.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3 text-xs"><span>مشروع #{lock.projectId} · {lock.periodMonth}/{lock.periodYear} · {lock.reason || "بدون سبب"}</span><Button type="button" size="sm" variant="outline" disabled={unlockPeriod.isPending} onClick={() => { const reason = window.prompt("اكتب سبب إعادة فتح الفترة"); if (reason?.trim()) unlockPeriod.mutate({ id: lock.id, reason: reason.trim() }); }}>إعادة فتح</Button></div>)}</div></CardContent></Card>
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg text-[#18324b]">مركز التنبيهات</CardTitle></CardHeader><CardContent className="space-y-2">{notifications.length ? notifications.slice(0, 8).map((note) => <button key={note.id} onClick={() => markRead.mutate({ id: note.id })} className={`w-full rounded-xl p-3 text-right text-sm ${note.readAt ? "bg-slate-50 text-slate-500" : "bg-amber-50 text-amber-800"}`}><p className="font-semibold">{note.title}</p><p className="mt-1 text-xs">{note.message}</p></button>) : <p className="py-6 text-center text-sm text-slate-400">لا توجد تنبيهات جديدة.</p>}</CardContent></Card>
    </section>
    <section className="grid gap-6 lg:grid-cols-2">
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg text-[#18324b]">آخر عمليات التدقيق</CardTitle></CardHeader><CardContent className="max-h-[360px] space-y-2 overflow-auto">{audit.slice(-10).reverse().map((entry) => <div key={entry.id} className="rounded-xl bg-slate-50 p-3 text-xs"><p className="font-semibold text-[#18324b]">{entry.entityType} #{entry.entityId} · {entry.action}</p><p className="mt-1 text-slate-500">بواسطة المستخدم #{entry.actorId}</p></div>)}</CardContent></Card>
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg text-[#18324b]">عضويات المشاريع</CardTitle></CardHeader><CardContent className="space-y-2">{members.length ? members.map((member) => <div key={member.id} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>مستخدم #{member.userId} · مشروع #{member.projectId}</span><span className="font-semibold text-[#18324b]">{roleLabels[member.projectRole]}</span></div>) : <p className="py-6 text-center text-sm text-slate-400">لم تُسند صلاحيات مشاريع بعد.</p>}</CardContent></Card>
    </section>
    <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg text-[#18324b]">مصفوفة صلاحيات العمليات</CardTitle><p className="text-xs leading-6 text-slate-500">اختر الزميل ثم حدد لكل عملية: تنفيذ مباشر، إحالة تلقائية للموافقة، أو منع كامل. حساب المسؤول له صلاحيات كاملة تلقائيًا.</p></CardHeader><CardContent className="space-y-4"><SelectField label="المستخدم المراد ضبطه" value={permissionUserId} options={users.filter((user) => user.role !== "admin").map((user) => ({ value: String(user.id), label: `${user.name || "بدون اسم"} — ${user.email || "بدون بريد"}` }))} onChange={setPermissionUserId} /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(operationPermissions?.operations ?? []).map((operation) => <div key={operation.key} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="mb-2 text-sm font-semibold text-[#18324b]">{operation.label}</p><select aria-label={`صلاحية ${operation.label}`} value={permissionModes[operation.key] || "approval"} onChange={(event) => setPermissionModes((current) => ({ ...current, [operation.key]: event.target.value as "allow" | "approval" | "deny" }))} className="h-10 w-full rounded-md border border-slate-200 bg-white px-2 text-sm"><option value="allow">مسموح مباشرة</option><option value="approval">يحتاج موافقة المسؤول</option><option value="deny">ممنوع</option></select></div>)}</div><Button className="w-full bg-[#18324b]" disabled={!permissionUserId || saveOperationPermissions.isPending} onClick={() => saveOperationPermissions.mutate({ userId: Number(permissionUserId), permissions: Object.entries(permissionModes).map(([operationKey, mode]) => ({ operationKey: operationKey as any, mode })) })}>حفظ مصفوفة الصلاحيات</Button></CardContent></Card>
  </div></div></DashboardLayout>;
}

function SelectField({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) { return <div className="space-y-2"><label className="text-sm text-slate-600">{label}</label><select required value={value} onChange={(e) => onChange(e.target.value)} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm"><option value="">اختر...</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>; }
